PCAN-View Linux: inc/dbc.h File Reference
dbc.h File Reference
Minimal CAN database (DBC) model, parser, and signal decoder.
#include <stddef.h>
#include <stdint.h>
Data Structures
struct dbc_signal_t
A single decoded-able signal within a message.
struct dbc_message_t
A CAN message definition with its signals.
struct dbc_db_t
A parsed CAN database (collection of messages).
Macros
#define DBC_NAME_MAX 64
Max message/signal name length.
#define DBC_UNIT_MAX 24
Max signal unit string length.
#define DBC_MAX_SIGNALS_PER_MSG 64
Max signals stored per message.
Functions
dbc_db_t * dbc_load_file (const char *path, char *err, size_t errsz)
Parse a DBC file into a new database.
void dbc_free (dbc_db_t *db)
Release a database returned by dbc_load_file.
const dbc_message_t * dbc_find_message (const dbc_db_t *db, uint32_t id, int is_extended)
Find the message definition matching a CAN identifier.
uint64_t dbc_extract_raw (const uint8_t *data, uint8_t dlc, const dbc_signal_t *sig)
Extract a signal's raw (unscaled) bit field from a payload.
double dbc_decode_physical (const dbc_signal_t *sig, uint64_t raw, int64_t *signed_raw_out)
Convert a raw field to its physical value.
Detailed Description
Minimal CAN database (DBC) model, parser, and signal decoder.
Provides a lightweight, GTK-independent representation of a Vector DBC file sufficient to drive the Signal Analysis view: a database (dbc_db_t) is a list of messages (dbc_message_t), each carrying a set of signals (dbc_signal_t). The parser understands the BO_ (message) and SG_ (signal) records of the DBC grammar — enough to decode real-world databases for monitoring — and the decoder extracts a signal's raw bits (Intel/little-endian or Motorola/big-endian) and converts them to a physical value via the linear factor/offset transform.
The module depends only on the C standard library so it can be unit-tested or reused outside the GUI.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file dbc.h.
Macro Definition Documentation
DBC_NAME_MAX
#define DBC_NAME_MAX 64
Max message/signal name length.
Definition at line 28 of file dbc.h.
DBC_UNIT_MAX
#define DBC_UNIT_MAX 24
Max signal unit string length.
Definition at line 29 of file dbc.h.
DBC_MAX_SIGNALS_PER_MSG
#define DBC_MAX_SIGNALS_PER_MSG 64
Max signals stored per message.
Definition at line 30 of file dbc.h.
Function Documentation
dbc_load_file()
dbc_db_t * dbc_load_file (const char * path, char * err, size_t errsz)
Parse a DBC file into a new database.
Parameters
path Path to the .dbc file.
err Optional buffer for a human-readable error (may be NULL).
errsz Size of err.
Returns
A new database (free with dbc_free), or NULL on failure.
Definition at line 135 of file dbc.c.
References dbc_free(), dbc_db_t::message_count, parse_bo(), parse_sg(), dbc_db_t::path, and dbc_db_t::signal_count.
Referenced by gui_signal_load_dbc().
dbc_free()
void dbc_free (dbc_db_t * db)
Release a database returned by dbc_load_file.
Parameters
db Database.
Definition at line 181 of file dbc.c.
References dbc_db_t::messages.
Referenced by dbc_load_file(), gui_signal_clear_dbc(), and gui_signal_load_dbc().
dbc_find_message()
const dbc_message_t * dbc_find_message (const dbc_db_t * db, uint32_t id, int is_extended)
Find the message definition matching a CAN identifier.
Parameters
db Database (may be NULL).
id Raw 11-/29-bit identifier.
is_extended Non-zero to match an extended-ID message.
Returns
The message, or NULL if not present.
Definition at line 189 of file dbc.c.
References dbc_message_t::id, dbc_message_t::is_extended, dbc_db_t::message_count, and dbc_db_t::messages.
Referenced by gui_signal_decode_message().
dbc_extract_raw()
uint64_t dbc_extract_raw (const uint8_t * data, uint8_t dlc, const dbc_signal_t * sig)
Extract a signal's raw (unscaled) bit field from a payload.
Parameters
data Payload bytes.
dlc Payload length in bytes.
sig Signal description.
Returns
The raw value, right-aligned (not sign-extended).
Definition at line 202 of file dbc.c.
References dbc_signal_t::length, dbc_signal_t::little_endian, dbc_signal_t::start_bit, and value.
Referenced by gui_signal_decode_message().
dbc_decode_physical()
double dbc_decode_physical (const dbc_signal_t * sig, uint64_t raw, int64_t * signed_raw_out)
Convert a raw field to its physical value.
Parameters
sig Signal description.
raw Raw value from dbc_extract_raw.
signed_raw_out Optional out: sign-extended raw as a signed integer.
Returns
The physical value (raw * factor + offset).
Definition at line 238 of file dbc.c.
References dbc_signal_t::factor, dbc_signal_t::is_signed, dbc_signal_t::length, and dbc_signal_t::offset.
Referenced by gui_signal_decode_message().