PCAN-View Linux: inc/drv_can.h File Reference
drv_can.h File Reference
Generic CAN driver abstraction (vtable) and thin wrapper API.
#include <stdint.h>
#include "can_message.h"
Data Structures
struct can_bit_timing_t
Optional manual CAN bit-timing parameters.
struct can_driver
CAN driver vtable — implemented by each concrete back-end.
Macros
#define DRV_CAN_OK 0
Operation succeeded.
#define DRV_CAN_ERR -1
Generic failure.
#define DRV_CAN_ERR_TIMEOUT -2
Operation timed out.
#define DRV_CAN_ERR_PARAM -3
Invalid argument.
#define DRV_CAN_ERR_INIT -4
Initialisation failed.
Typedefs
typedef struct can_driver can_driver_t
CAN driver vtable — implemented by each concrete back-end.
Enumerations
enum can_baud_t {
CAN_BAUD_10K = 10000 , CAN_BAUD_20K = 20000 , CAN_BAUD_50K = 50000 , CAN_BAUD_100K = 100000 ,
CAN_BAUD_125K = 125000 , CAN_BAUD_250K = 250000 , CAN_BAUD_500K = 500000 , CAN_BAUD_800K = 800000 ,
CAN_BAUD_1M = 1000000
}
Standard nominal CAN bit rates (bit/s).
enum can_fd_baud_t {
CAN_FD_BAUD_1M = 1000000 , CAN_FD_BAUD_2M = 2000000 , CAN_FD_BAUD_4M = 4000000 , CAN_FD_BAUD_5M = 5000000 ,
CAN_FD_BAUD_8M = 8000000 , CAN_FD_BAUD_10M = 10000000
}
Standard CAN FD data-phase bit rates (bit/s).
Functions
struct can_driver * drv_can_get_socketcan (void)
Return the built-in SocketCAN driver vtable singleton.
int drv_can_init (can_driver_t *drv, const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Select a driver and open/configure a CAN interface.
int drv_can_deinit (void)
Close the active interface and release driver resources.
int drv_can_send (const can_msg_t *msg)
Transmit a single frame.
int drv_can_recv (can_msg_t *msg, int timeout_ms)
Receive a single frame, blocking up to timeout_ms.
int drv_can_get_stats (can_stats_t *stats)
Query driver statistics.
int drv_can_set_filter (uint32_t id, uint32_t mask, int is_extended)
Install a hardware acceptance filter.
int drv_can_clear_filter (void)
Remove all acceptance filters (accept everything).
int drv_can_reset (void)
Reset the CAN controller/interface.
const char * drv_can_error_string (int err)
Translate a DRV_CAN_* code to a human-readable string.
Detailed Description
Generic CAN driver abstraction (vtable) and thin wrapper API.
Declares the back-end-agnostic CAN driver interface used by the rest of the application. A concrete back-end (currently SocketCAN, see driver/socketcan.c) provides a can_driver_t function-pointer table; the drv_can_* wrapper functions in driver/drv_can.c dispatch to the currently selected driver. Adding a new back-end (e.g. PCAN-Basic) only requires implementing the vtable and passing it to drv_can_init.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file drv_can.h.
Macro Definition Documentation
DRV_CAN_OK
#define DRV_CAN_OK 0
Operation succeeded.
Definition at line 23 of file drv_can.h.
DRV_CAN_ERR
#define DRV_CAN_ERR -1
Generic failure.
Definition at line 24 of file drv_can.h.
DRV_CAN_ERR_TIMEOUT
#define DRV_CAN_ERR_TIMEOUT -2
Operation timed out.
Definition at line 25 of file drv_can.h.
DRV_CAN_ERR_PARAM
#define DRV_CAN_ERR_PARAM -3
Invalid argument.
Definition at line 26 of file drv_can.h.
DRV_CAN_ERR_INIT
#define DRV_CAN_ERR_INIT -4
Initialisation failed.
Definition at line 27 of file drv_can.h.
Typedef Documentation
can_driver_t
typedef struct can_driver can_driver_t
CAN driver vtable — implemented by each concrete back-end.
Every member is a function pointer mirroring one drv_can_* wrapper.
Enumeration Type Documentation
can_baud_t
enum can_baud_t
Standard nominal CAN bit rates (bit/s).
Enumerator
CAN_BAUD_10K
CAN_BAUD_20K
CAN_BAUD_50K
CAN_BAUD_100K
CAN_BAUD_125K
CAN_BAUD_250K
CAN_BAUD_500K
CAN_BAUD_800K
CAN_BAUD_1M
Definition at line 30 of file drv_can.h.
can_fd_baud_t
enum can_fd_baud_t
Standard CAN FD data-phase bit rates (bit/s).
Enumerator
CAN_FD_BAUD_1M
CAN_FD_BAUD_2M
CAN_FD_BAUD_4M
CAN_FD_BAUD_5M
CAN_FD_BAUD_8M
CAN_FD_BAUD_10M
Definition at line 43 of file drv_can.h.
Function Documentation
drv_can_get_socketcan()
struct can_driver * drv_can_get_socketcan (void)
Return the built-in SocketCAN driver vtable singleton.
Returns
Pointer to a statically allocated can_driver_t.
Definition at line 93 of file drv_can.c.
References s_socketcan_driver.
Referenced by app_do_connect().
drv_can_init()
int drv_can_init (can_driver_t * drv, const char * iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t * timing)
Select a driver and open/configure a CAN interface.
Parameters
drv Driver vtable to use (e.g. from drv_can_get_socketcan).
iface Interface name (e.g. "can0", "vcan0").
bitrate Nominal bit rate in bit/s.
data_bitrate CAN FD data-phase bit rate in bit/s (0 if unused).
fd_mode Non-zero to enable CAN FD.
listen_only Non-zero for passive (no-ACK) monitoring.
timing Optional manual bit timing (may be NULL).
Returns
DRV_CAN_OK on success or a negative DRV_CAN_ERR_* code.
< Invalid argument.
Definition at line 101 of file drv_can.c.
References DRV_CAN_ERR_PARAM, can_driver::init, and s_active_drv.
Referenced by app_do_connect().
drv_can_deinit()
int drv_can_deinit (void)
Close the active interface and release driver resources.
Returns
Status code.
< Initialisation failed.
Definition at line 111 of file drv_can.c.
References can_driver::deinit, DRV_CAN_ERR_INIT, and s_active_drv.
Referenced by app_do_disconnect().
drv_can_send()
int drv_can_send (const can_msg_t * msg)
Transmit a single frame.
Parameters
msg Frame to send.
Returns
Status code.
< Initialisation failed.
Definition at line 119 of file drv_can.c.
References DRV_CAN_ERR_INIT, s_active_drv, and can_driver::send.
Referenced by thread_tx().
drv_can_recv()
int drv_can_recv (can_msg_t * msg, int timeout_ms)
Receive a single frame, blocking up to timeout_ms.
Parameters
msg Output frame.
timeout_ms Timeout in milliseconds (<0 to block indefinitely).
Returns
DRV_CAN_OK, DRV_CAN_ERR_TIMEOUT, or another DRV_CAN_ERR_* code.
< Initialisation failed.
Definition at line 125 of file drv_can.c.
References DRV_CAN_ERR_INIT, can_driver::recv, and s_active_drv.
Referenced by thread_rx().
drv_can_get_stats()
int drv_can_get_stats (can_stats_t * stats)
Query driver statistics.
Parameters
stats Output snapshot.
Returns
Status code.
< Initialisation failed.
Definition at line 131 of file drv_can.c.
References DRV_CAN_ERR_INIT, can_driver::get_stats, and s_active_drv.
drv_can_set_filter()
int drv_can_set_filter (uint32_t id, uint32_t mask, int is_extended)
Install a hardware acceptance filter.
Parameters
id Filter identifier.
mask Filter mask.
is_extended Non-zero for a 29-bit filter.
Returns
Status code.
< Initialisation failed.
Definition at line 137 of file drv_can.c.
References DRV_CAN_ERR_INIT, s_active_drv, and can_driver::set_filter.
drv_can_clear_filter()
int drv_can_clear_filter (void)
Remove all acceptance filters (accept everything).
Returns
Status code.
< Initialisation failed.
Definition at line 143 of file drv_can.c.
References can_driver::clear_filter, DRV_CAN_ERR_INIT, and s_active_drv.
drv_can_reset()
int drv_can_reset (void)
Reset the CAN controller/interface.
Returns
Status code.
< Initialisation failed.
Definition at line 149 of file drv_can.c.
References DRV_CAN_ERR_INIT, can_driver::reset, and s_active_drv.
drv_can_error_string()
const char * drv_can_error_string (int err)
Translate a DRV_CAN_* code to a human-readable string.
Parameters
err Code.
Returns
Static string.
Definition at line 155 of file drv_can.c.
References can_driver::error_string, s_active_drv, and socketcan_error_string().
Referenced by app_do_connect().