PCAN-View Linux: driver/drv_can.c File Reference
drv_can.c File Reference
Generic CAN driver abstraction and the SocketCAN binding.
#include <stdio.h>
#include <string.h>
#include "../inc/drv_can.h"
#include "../inc/socketcan.h"
Functions
can_driver_t * drv_can_get_socketcan (void)
Return the built-in SocketCAN driver vtable singleton.
int drv_can_init (can_driver_t *drv, const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Select a driver and open/configure a CAN interface.
int drv_can_deinit (void)
Close the active interface and release driver resources.
int drv_can_send (const can_msg_t *msg)
Transmit a single frame.
int drv_can_recv (can_msg_t *msg, int timeout_ms)
Receive a single frame, blocking up to timeout_ms.
int drv_can_get_stats (can_stats_t *stats)
Query driver statistics.
int drv_can_set_filter (uint32_t id, uint32_t mask, int is_extended)
Install a hardware acceptance filter.
int drv_can_clear_filter (void)
Remove all acceptance filters (accept everything).
int drv_can_reset (void)
Reset the CAN controller/interface.
const char * drv_can_error_string (int err)
Translate a DRV_CAN_* code to a human-readable string.
Variables
static can_driver_t * s_active_drv = NULL
Currently selected driver vtable, or NULL when disconnected.
SocketCAN vtable adapters
Thin wrappers binding s_sck_ctx to the socketcan_* calls.
static socketcan_ctx_t s_sck_ctx
Per-process SocketCAN connection context.
static can_driver_t s_socketcan_driver
The built-in SocketCAN driver vtable.
static int sck_init (const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
static int sck_deinit (void)
static int sck_send (const can_msg_t *msg)
static int sck_recv (can_msg_t *msg, int timeout_ms)
static int sck_get_stats (can_stats_t *stats)
static int sck_set_filter (uint32_t id, uint32_t mask, int is_extended)
static int sck_clear_filter (void)
static int sck_reset (void)
static const char * sck_error_string (int err)
Detailed Description
Generic CAN driver abstraction and the SocketCAN binding.
Implements the hardware-independent drv_can_* API declared in drv_can.h. Each call dispatches through the currently selected can_driver_t vtable (set by drv_can_init). This file also defines the built-in SocketCAN vtable, whose members are thin adapters that forward to the socketcan_* functions while binding the shared s_sck_ctx.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file drv_can.c.
Function Documentation
sck_init()
static int sck_init (const char * iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t * timing) static
Definition at line 31 of file drv_can.c.
References s_sck_ctx, and socketcan_open().
sck_deinit()
static int sck_deinit (void) static
Definition at line 39 of file drv_can.c.
References s_sck_ctx, and socketcan_close().
sck_send()
static int sck_send (const can_msg_t * msg) static
Definition at line 44 of file drv_can.c.
References s_sck_ctx, and socketcan_send().
sck_recv()
static int sck_recv (can_msg_t * msg, int timeout_ms) static
Definition at line 49 of file drv_can.c.
References s_sck_ctx, and socketcan_recv().
sck_get_stats()
static int sck_get_stats (can_stats_t * stats) static
Definition at line 54 of file drv_can.c.
References s_sck_ctx, and socketcan_get_stats().
sck_set_filter()
static int sck_set_filter (uint32_t id, uint32_t mask, int is_extended) static
Definition at line 59 of file drv_can.c.
References s_sck_ctx, and socketcan_set_filter().
sck_clear_filter()
static int sck_clear_filter (void) static
Definition at line 64 of file drv_can.c.
References s_sck_ctx, and socketcan_clear_filter().
sck_reset()
static int sck_reset (void) static
Definition at line 69 of file drv_can.c.
References s_sck_ctx, and socketcan_reset().
sck_error_string()
static const char * sck_error_string (int err) static
Definition at line 74 of file drv_can.c.
References socketcan_error_string().
drv_can_get_socketcan()
can_driver_t * drv_can_get_socketcan (void)
Return the built-in SocketCAN driver vtable singleton.
Returns
Pointer to a statically allocated can_driver_t.
Definition at line 93 of file drv_can.c.
References s_socketcan_driver.
Referenced by app_do_connect().
drv_can_init()
int drv_can_init (can_driver_t * drv, const char * iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t * timing)
Select a driver and open/configure a CAN interface.
Parameters
drv Driver vtable to use (e.g. from drv_can_get_socketcan).
iface Interface name (e.g. "can0", "vcan0").
bitrate Nominal bit rate in bit/s.
data_bitrate CAN FD data-phase bit rate in bit/s (0 if unused).
fd_mode Non-zero to enable CAN FD.
listen_only Non-zero for passive (no-ACK) monitoring.
timing Optional manual bit timing (may be NULL).
Returns
DRV_CAN_OK on success or a negative DRV_CAN_ERR_* code.
< Invalid argument.
Definition at line 101 of file drv_can.c.
References DRV_CAN_ERR_PARAM, can_driver::init, and s_active_drv.
Referenced by app_do_connect().
drv_can_deinit()
int drv_can_deinit (void)
Close the active interface and release driver resources.
Returns
Status code.
< Initialisation failed.
Definition at line 111 of file drv_can.c.
References can_driver::deinit, DRV_CAN_ERR_INIT, and s_active_drv.
Referenced by app_do_disconnect().
drv_can_send()
int drv_can_send (const can_msg_t * msg)
Transmit a single frame.
Parameters
msg Frame to send.
Returns
Status code.
< Initialisation failed.
Definition at line 119 of file drv_can.c.
References DRV_CAN_ERR_INIT, s_active_drv, and can_driver::send.
Referenced by thread_tx().
drv_can_recv()
int drv_can_recv (can_msg_t * msg, int timeout_ms)
Receive a single frame, blocking up to timeout_ms.
Parameters
msg Output frame.
timeout_ms Timeout in milliseconds (<0 to block indefinitely).
Returns
DRV_CAN_OK, DRV_CAN_ERR_TIMEOUT, or another DRV_CAN_ERR_* code.
< Initialisation failed.
Definition at line 125 of file drv_can.c.
References DRV_CAN_ERR_INIT, can_driver::recv, and s_active_drv.
Referenced by thread_rx().
drv_can_get_stats()
int drv_can_get_stats (can_stats_t * stats)
Query driver statistics.
Parameters
stats Output snapshot.
Returns
Status code.
< Initialisation failed.
Definition at line 131 of file drv_can.c.
References DRV_CAN_ERR_INIT, can_driver::get_stats, and s_active_drv.
drv_can_set_filter()
int drv_can_set_filter (uint32_t id, uint32_t mask, int is_extended)
Install a hardware acceptance filter.
Parameters
id Filter identifier.
mask Filter mask.
is_extended Non-zero for a 29-bit filter.
Returns
Status code.
< Initialisation failed.
Definition at line 137 of file drv_can.c.
References DRV_CAN_ERR_INIT, s_active_drv, and can_driver::set_filter.
drv_can_clear_filter()
int drv_can_clear_filter (void)
Remove all acceptance filters (accept everything).
Returns
Status code.
< Initialisation failed.
Definition at line 143 of file drv_can.c.
References can_driver::clear_filter, DRV_CAN_ERR_INIT, and s_active_drv.
drv_can_reset()
int drv_can_reset (void)
Reset the CAN controller/interface.
Returns
Status code.
< Initialisation failed.
Definition at line 149 of file drv_can.c.
References DRV_CAN_ERR_INIT, can_driver::reset, and s_active_drv.
drv_can_error_string()
const char * drv_can_error_string (int err)
Translate a DRV_CAN_* code to a human-readable string.
Parameters
err Code.
Returns
Static string.
Definition at line 155 of file drv_can.c.
References can_driver::error_string, s_active_drv, and socketcan_error_string().
Referenced by app_do_connect().
Variable Documentation
s_sck_ctx
socketcan_ctx_t s_sck_ctx static
Per-process SocketCAN connection context.
Definition at line 29 of file drv_can.c.
Referenced by sck_clear_filter(), sck_deinit(), sck_get_stats(), sck_init(), sck_recv(), sck_reset(), sck_send(), and sck_set_filter().
s_socketcan_driver
can_driver_t s_socketcan_driver static
Initial value:
= {
    .init         = sck_init,
    .deinit       = sck_deinit,
    .send         = sck_send,
    .recv         = sck_recv,
    .get_stats    = sck_get_stats,
    .set_filter   = sck_set_filter,
    .clear_filter = sck_clear_filter,
    .reset        = sck_reset,
    .error_string = sck_error_string,
}
The built-in SocketCAN driver vtable.
Definition at line 80 of file drv_can.c.
Referenced by drv_can_get_socketcan().
s_active_drv
can_driver_t* s_active_drv = NULL static
Currently selected driver vtable, or NULL when disconnected.
Definition at line 99 of file drv_can.c.
Referenced by drv_can_clear_filter(), drv_can_deinit(), drv_can_error_string(), drv_can_get_stats(), drv_can_init(), drv_can_recv(), drv_can_reset(), drv_can_send(), and drv_can_set_filter().