PCAN-View Linux: inc/gui.h File Reference
gui.h File Reference
GTK GUI widget registry and the application's GUI/thread API.
#include <gtk/gtk.h>
#include "can_message.h"
#include "app_state.h"
#include "dbc.h"
Data Structures
struct gui_widgets_t
Bundle of long-lived widgets, populated by gui_create_main_window.
Enumerations
enum {
TCOL_SEQ = 0 , TCOL_DIR , TCOL_TIME , TCOL_ID ,
TCOL_TYPE , TCOL_DLC , TCOL_DATA , TCOL_INTERVAL ,
TCOL_FREQ , TCOL_COUNT , TCOL_FG , TCOL_ID_RAW ,
TCOL_EXT_RAW , TCOL_DIR_RAW , TCOL_DATA_RAW , TCOL_TS_NS ,
TCOL_NUM
}
Column indices of the trace GtkListStore.
Functions
GtkWidget * gui_create_main_window (GtkApplication *app)
Build the main application window and all of its widgets.
void gui_tx_panel_update_fd (void)
Sync the transmit panel with the current CAN FD link mode.
void gui_add_message (const can_msg_t *msg)
Append (or roll up) one frame into the trace view.
void gui_clear_trace (void)
Remove every row from the trace view.
void gui_refresh_trace_display (void)
Re-render existing trace rows after a display-format change.
GtkWidget * gui_create_signal_view (void)
Build the Signal Analysis tab (live DBC-decoded signal table).
gboolean gui_signal_load_dbc (const char *path)
Load (or replace) the active CAN database for signal decoding.
void gui_signal_load_default_dbc (void)
Auto-load the bundled demo database if one is found.
void gui_signal_clear_dbc (void)
Forget the active database and clear the signal table.
void gui_signal_decode_message (const can_msg_t *msg)
Decode one frame against the active database and update the signal rows.
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
void gui_plot_set_database (const dbc_db_t *db)
Rebuild the plot's series list from a database (or clear it).
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
void gui_update_stats (void)
Refresh the statistics bar from g_app counters.
void gui_status_message (const char *fmt,...)
Set the status-bar text (printf-style).
void gui_show_settings_dialog (GtkWidget *parent)
Show the connection-settings dialog.
void gui_show_transmit_window (void)
Show the advanced transmit window.
void gui_show_about_dialog (GtkWidget *parent)
Show the About dialog (Taksys branding).
void gui_show_error (GtkWidget *parent, const char *title, const char *msg)
Show a modal error dialog.
void gui_format_id (char *buf, size_t sz, uint32_t id, int is_ext)
Format a CAN identifier into buf per the active display radix.
void gui_format_data (char *buf, size_t sz, const uint8_t *d, uint8_t dlc)
Format payload bytes into buf per the active data format.
const char * gui_msg_type_str (const can_msg_t *m)
Return a short frame-type label ("Std", "Ext", "FD+BRS", …).
const char * gui_bus_state_str (uint8_t st)
Return a bus-state label for a CAN_BUS_* value.
const char * gui_bus_state_color (uint8_t st)
Return a Pango colour name for a CAN_BUS_* value.
void * thread_rx (void *arg)
Receive-thread entry point.
void * thread_tx (void *arg)
Transmit-thread entry point.
void * thread_stats (void *arg)
Statistics-thread entry point.
void app_do_connect (void)
Open the interface in g_app and start the worker threads.
void app_do_disconnect (void)
Stop the worker threads and close the interface.
Variables
gui_widgets_t g_gui
The process-wide GUI widget registry (defined in threads.c).
Detailed Description
GTK GUI widget registry and the application's GUI/thread API.
Declares the trace-view column layout, the global widget bundle (gui_widgets_t / g_gui), and every public function implemented by the gui/ sources: window construction, trace/statistics updates, dialogs, value formatting, the RX/TX/stats thread entry points, and the connect/disconnect lifecycle helpers.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file gui.h.
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indices of the trace GtkListStore.
Columns up to TCOL_COUNT are visible; the remainder are hidden helper columns used for sorting, row roll-up, and re-formatting.
Enumerator
TCOL_SEQ
Sequence number.
TCOL_DIR
Direction ("Rx"/"Tx").
TCOL_TIME
Formatted timestamp.
TCOL_ID
Formatted CAN identifier.
TCOL_TYPE
Frame type string.
TCOL_DLC
Data length code.
TCOL_DATA
Formatted payload.
TCOL_INTERVAL
Inter-frame interval (ms).
TCOL_FREQ
Frame frequency (Hz).
TCOL_COUNT
Hit count for rolled-up rows.
TCOL_FG
Row foreground colour (markup).
TCOL_ID_RAW
Hidden numeric ID for sorting / reformatting.
TCOL_EXT_RAW
Hidden extended-ID flag.
TCOL_DIR_RAW
Hidden direction flag for row roll-up.
TCOL_DATA_RAW
Hidden compact hex data for reformatting.
TCOL_TS_NS
Hidden last timestamp in nanoseconds.
TCOL_NUM
Number of columns (model width).
Definition at line 30 of file gui.h.
Function Documentation
gui_create_main_window()
GtkWidget * gui_create_main_window (GtkApplication * app)
Build the main application window and all of its widgets.
Parameters
app The owning GtkApplication.
Returns
The newly created top-level window.
Definition at line 1442 of file main_window.c.
References build_menubar(), build_stats_bar(), build_toolbar(), create_trace_view(), create_transmit_panel(), g_gui, gui_create_signal_plot(), gui_create_signal_view(), gui_load_logo(), gui_signal_load_default_dbc(), gui_update_stats(), on_key_press(), on_window_delete(), gui_widgets_t::statusbar, gui_widgets_t::statusbar_ctx, and gui_widgets_t::window.
Referenced by on_app_activate().
gui_tx_panel_update_fd()
void gui_tx_panel_update_fd (void)
Sync the transmit panel with the current CAN FD link mode.
Widens each row's DLC range to 64 in CAN FD mode (8 in classic) and refreshes the number of visible data-byte fields.
< Maximum payload of a CAN FD frame.
< Maximum payload of a classic CAN frame.
Definition at line 1421 of file main_window.c.
References CAN_MAX_DLC, CANFD_DATA_MAX, tx_panel_row_t::dlc_spin, app_state_t::fd_mode, g_app, s_txp, and txp_update_data_fields().
Referenced by app_do_connect(), and create_transmit_panel().
gui_add_message()
void gui_add_message (const can_msg_t * msg)
Append (or roll up) one frame into the trace view.
Parameters
msg Frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Frame direction: transmitted.
Definition at line 383 of file message_view.c.
References CAN_DIR_TX, can_msg_t::data, DATA_TEXT_MAX, can_msg_t::direction, can_msg_t::dlc, format_frequency(), format_interval(), format_raw_data(), format_timestamp(), FREQ_TEXT_MAX, g_gui, gui_format_data(), gui_format_id(), gui_msg_type_str(), gui_signal_decode_message(), can_msg_t::id, ID_TEXT_MAX, INTERVAL_TEXT_MAX, can_msg_t::is_extended, MAX_TRACE_ROWS, RAW_DATA_MAX, row_fg(), can_msg_t::seq, should_rollup_message(), TCOL_COUNT, TCOL_DATA, TCOL_DATA_RAW, TCOL_DIR, TCOL_DIR_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_FG, TCOL_FREQ, TCOL_ID, TCOL_ID_RAW, TCOL_INTERVAL, TCOL_SEQ, TCOL_TIME, TCOL_TS_NS, TCOL_TYPE, TIME_TEXT_MAX, timespec_to_ns(), can_msg_t::timestamp, gui_widgets_t::trace_store, and gui_widgets_t::trace_view.
Referenced by idle_add_message().
gui_clear_trace()
void gui_clear_trace (void)
Remove every row from the trace view.
Definition at line 516 of file message_view.c.
References g_gui, and gui_widgets_t::trace_store.
Referenced by on_clear(), and on_dedup_toggle().
gui_refresh_trace_display()
void gui_refresh_trace_display (void)
Re-render existing trace rows after a display-format change.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 522 of file message_view.c.
References CANFD_DATA_MAX, DATA_TEXT_MAX, g_gui, gui_format_data(), gui_format_id(), ID_TEXT_MAX, parse_raw_data(), TCOL_DATA, TCOL_DATA_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_ID, TCOL_ID_RAW, and gui_widgets_t::trace_store.
Referenced by on_data_format_toggle(), and on_id_format_toggle().
gui_create_signal_view()
GtkWidget * gui_create_signal_view (void)
Build the Signal Analysis tab (live DBC-decoded signal table).
Returns
A container widget for use as a notebook page.
Definition at line 312 of file signal_view.c.
References g_gui, gui_widgets_t::lbl_dbc, on_clear_dbc(), on_load_dbc(), on_reload_dbc(), SCOL_COUNT, SCOL_FG, SCOL_ID, SCOL_MSG, SCOL_NUM, SCOL_RANGE, SCOL_RAW, SCOL_SIGNAL, SCOL_UNIT, SCOL_VALUE, gui_widgets_t::sig_store, sig_update_dbc_label(), and gui_widgets_t::sig_view.
Referenced by gui_create_main_window().
gui_signal_load_dbc()
gboolean gui_signal_load_dbc (const char * path)
Load (or replace) the active CAN database for signal decoding.
Parameters
path Path to a .dbc file.
Returns
TRUE on success; on failure a status message is shown and the previous database (if any) is kept.
Definition at line 152 of file signal_view.c.
References dbc_free(), dbc_load_file(), gui_plot_set_database(), gui_status_message(), dbc_db_t::message_count, dbc_db_t::path, s_db, sig_table_rebuild(), sig_update_dbc_label(), and dbc_db_t::signal_count.
Referenced by gui_signal_load_default_dbc(), on_db_load(), on_load_dbc(), and on_reload_dbc().
gui_signal_load_default_dbc()
void gui_signal_load_default_dbc (void)
Auto-load the bundled demo database if one is found.
Definition at line 188 of file signal_view.c.
References gui_find_asset(), gui_signal_load_dbc(), and sig_update_dbc_label().
Referenced by gui_create_main_window(), on_db_demo(), and on_reload_dbc().
gui_signal_clear_dbc()
void gui_signal_clear_dbc (void)
Forget the active database and clear the signal table.
Definition at line 176 of file signal_view.c.
References dbc_free(), gui_plot_set_database(), gui_status_message(), s_db, sig_table_rebuild(), and sig_update_dbc_label().
Referenced by on_clear_dbc(), and on_db_clear().
gui_signal_decode_message()
void gui_signal_decode_message (const can_msg_t * msg)
Decode one frame against the active database and update the signal rows.
Parameters
msg Frame (RX or TX); ignored when no database is loaded.
< Frame direction: transmitted.
Definition at line 201 of file signal_view.c.
References CAN_DIR_TX, can_msg_t::data, dbc_decode_physical(), dbc_extract_raw(), dbc_find_message(), can_msg_t::direction, can_msg_t::dlc, fmt_double(), g_gui, gui_plot_add_sample(), can_msg_t::id, dbc_message_t::id, can_msg_t::is_error, can_msg_t::is_extended, dbc_message_t::is_extended, s_db, SCOL_COUNT, SCOL_EXT, SCOL_FG, SCOL_MSGID, SCOL_RAW, SCOL_SIGIDX, SCOL_VALUE, gui_widgets_t::sig_store, dbc_message_t::signal_count, and dbc_message_t::signals.
Referenced by gui_add_message().
gui_create_signal_plot()
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
Returns
A container widget for use as a notebook page.
< Redraw period (~30 fps) while mapped.
Definition at line 453 of file signal_plot.c.
References on_destroy(), on_draw(), on_pause(), on_reset(), on_select_all(), on_select_none(), on_window_changed(), PLOT_REDRAW_MS, plot_tick(), and s_plot.
Referenced by gui_create_main_window().
gui_plot_set_database()
void gui_plot_set_database (const dbc_db_t * db)
Rebuild the plot's series list from a database (or clear it).
Parameters
db Active database, or NULL to remove all series.
< Max message/signal name length.
Definition at line 121 of file signal_plot.c.
References plot_series_t::check, plot_series_t::col, DBC_NAME_MAX, plot_series_t::dmax, plot_series_t::dmin, plot_series_t::enabled, plot_series_t::ext, plot_series_t::id, dbc_message_t::id, dbc_message_t::is_extended, plot_series_t::label, dbc_signal_t::max, dbc_db_t::message_count, dbc_db_t::messages, dbc_signal_t::min, dbc_signal_t::name, dbc_message_t::name, on_series_toggled(), PALETTE, PALETTE_N, plot_free_series(), s_plot, plot_series_t::sig_idx, dbc_message_t::signal_count, dbc_db_t::signal_count, dbc_message_t::signals, plot_series_t::unit, and dbc_signal_t::unit.
Referenced by gui_signal_clear_dbc(), and gui_signal_load_dbc().
gui_plot_add_sample()
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
Parameters
id Raw CAN identifier.
is_ext Non-zero for an extended-ID message.
sig_idx Signal index within its message.
value Physical value.
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
Definition at line 185 of file signal_plot.c.
References plot_series_t::count, plot_series_t::ext, plot_series_t::has_last, plot_series_t::head, plot_series_t::id, plot_series_t::last, plot_now(), PLOT_RING, s_plot, plot_series_t::sig_idx, plot_series_t::t, plot_series_t::v, and value.
Referenced by gui_signal_decode_message().
gui_update_stats()
void gui_update_stats (void)
Refresh the statistics bar from g_app counters.
Definition at line 568 of file message_view.c.
References app_state_t::bitrate, app_state_t::bus_load, app_state_t::bus_state, app_state_t::connected, app_state_t::error_count, g_app, g_gui, gui_bus_state_color(), gui_bus_state_str(), app_state_t::iface, gui_widgets_t::lbl_bitrate, gui_widgets_t::lbl_bus_load, gui_widgets_t::lbl_bus_state, gui_widgets_t::lbl_connection, gui_widgets_t::lbl_err, gui_widgets_t::lbl_rx, gui_widgets_t::lbl_stats_summary, gui_widgets_t::lbl_tx, gui_widgets_t::progress_bus_load, app_state_t::rx_count, and app_state_t::tx_count.
Referenced by app_do_disconnect(), gui_create_main_window(), and idle_update_stats().
gui_status_message()
void gui_status_message (const char * fmt, ...)
Set the status-bar text (printf-style).
Parameters
fmt printf format string.
... Format arguments.
Definition at line 638 of file message_view.c.
References g_gui, gui_widgets_t::statusbar, and gui_widgets_t::statusbar_ctx.
Referenced by app_do_connect(), app_do_disconnect(), gui_signal_clear_dbc(), gui_signal_load_dbc(), on_clear(), on_data_format_toggle(), on_dedup_toggle(), on_id_format_toggle(), on_trace_save(), on_trace_start(), and on_trace_stop().
gui_show_settings_dialog()
void gui_show_settings_dialog (GtkWidget * parent)
Show the connection-settings dialog.
Parameters
parent Transient parent.
< Max interface-name length in app state.
Definition at line 117 of file settings_dialog.c.
References app_do_connect(), app_do_disconnect(), APP_MAX_IFACE_LEN, app_state_t::bitrate, app_state_t::connected, app_state_t::data_bitrate, app_state_t::fd_mode, g_app, GRID_LABEL, app_state_t::iface, label, app_state_t::listen_only, on_fd_toggled(), populate_interfaces(), s_bitrates, s_fd_bitrates, and value.
Referenced by on_connect(), and on_settings().
gui_show_transmit_window()
void gui_show_transmit_window (void)
Show the advanced transmit window.
Definition at line 284 of file transmit_dialog.c.
References tx_win_t::brs_check, tx_win_t::cyclic_btn_start, tx_win_t::cyclic_btn_stop, tx_win_t::data_entry, tx_win_t::data_grid, tx_win_t::dlc_spin, tx_win_t::ext_check, tx_win_t::fd_check, FLABEL, g_gui, tx_win_t::id_entry, tx_win_t::interval_spin, MAX_DATA_ENTRIES, on_cyclic_start(), on_cyclic_stop(), on_dlc_changed(), on_fd_toggled(), on_rtr_toggled(), on_send_once(), on_tx_win_destroy(), tx_win_t::rtr_check, s_tx, tx_win_t::status_label, tx_win_t::window, and gui_widgets_t::window.
Referenced by on_transmit().
gui_show_about_dialog()
void gui_show_about_dialog (GtkWidget * parent)
Show the About dialog (Taksys branding).
Parameters
parent Transient parent.
Definition at line 1564 of file main_window.c.
References gui_load_logo(), PCAN_VIEW_APP_NAME, PCAN_VIEW_COPYRIGHT, PCAN_VIEW_VENDOR, and PCAN_VIEW_VERSION.
Referenced by on_about().
gui_show_error()
void gui_show_error (GtkWidget * parent, const char * title, const char * msg)
Show a modal error dialog.
Parameters
parent Transient parent (may be NULL).
title Window title.
msg Message body.
Definition at line 656 of file message_view.c.
Referenced by app_do_connect(), on_trace_save(), and on_trace_start().
gui_format_id()
void gui_format_id (char * buf, size_t sz, uint32_t id, int is_ext)
Format a CAN identifier into buf per the active display radix.
Parameters
buf Output buffer.
sz Buffer size.
id Identifier value.
is_ext Non-zero for an extended (29-bit) ID.
Definition at line 44 of file message_view.c.
References APP_ID_FORMAT_DEC, g_app, and app_state_t::id_format.
Referenced by gui_add_message(), gui_refresh_trace_display(), and sig_table_rebuild().
gui_format_data()
void gui_format_data (char * buf, size_t sz, const uint8_t * d, uint8_t dlc)
Format payload bytes into buf per the active data format.
Parameters
buf Output buffer.
sz Buffer size.
d Payload bytes.
dlc Number of bytes.
Definition at line 57 of file message_view.c.
References APP_DATA_FORMAT_ASCII, APP_DATA_FORMAT_DEC, app_state_t::data_format, and g_app.
Referenced by gui_add_message(), and gui_refresh_trace_display().
gui_msg_type_str()
const char * gui_msg_type_str (const can_msg_t * m)
Return a short frame-type label ("Std", "Ext", "FD+BRS", …).
Parameters
m Frame.
Returns
Static string.
Definition at line 197 of file message_view.c.
References can_msg_t::is_brs, can_msg_t::is_error, can_msg_t::is_extended, can_msg_t::is_fd, and can_msg_t::is_remote.
Referenced by gui_add_message(), and trace_csv_write_row().
gui_bus_state_str()
const char * gui_bus_state_str (uint8_t st)
Return a bus-state label for a CAN_BUS_* value.
Parameters
st State.
Returns
Static string.
< Error-warning bus state.
< Error-passive bus state.
< Bus-off state.
Definition at line 205 of file message_view.c.
References CAN_BUS_OFF, CAN_BUS_PASSIVE, and CAN_BUS_WARNING.
Referenced by gui_update_stats().
gui_bus_state_color()
const char * gui_bus_state_color (uint8_t st)
Return a Pango colour name for a CAN_BUS_* value.
Parameters
st State.
Returns
Static string.
< Error-warning bus state.
< Error-passive bus state.
< Bus-off state.
Definition at line 215 of file message_view.c.
References CAN_BUS_OFF, CAN_BUS_PASSIVE, and CAN_BUS_WARNING.
Referenced by gui_update_stats().
thread_rx()
void * thread_rx (void * arg)
Receive-thread entry point.
Parameters
arg Unused.
Returns
NULL.
< Operation succeeded.
< Frame direction: received.
Definition at line 163 of file threads.c.
References CAN_DIR_RX, can_msg_t::direction, can_msg_t::dlc, DRV_CAN_OK, drv_can_recv(), app_state_t::error_count, g_app, idle_add_message(), can_msg_t::is_error, can_msg_t::is_extended, app_state_t::msg_seq, app_state_t::period_bits, app_state_t::rx_count, app_state_t::rx_running, can_msg_t::seq, and trace_record().
Referenced by app_do_connect().
thread_tx()
void * thread_tx (void * arg)
Transmit-thread entry point.
Parameters
arg Unused.
Returns
NULL.
< Operation succeeded.
< Frame direction: transmitted.
Definition at line 204 of file threads.c.
References CAN_DIR_TX, can_msg_t::direction, DRV_CAN_OK, drv_can_send(), g_app, idle_update_stats(), app_state_t::msg_seq, can_msg_t::seq, can_msg_t::timestamp, trace_record(), app_state_t::tx_count, app_state_t::tx_queue, and app_state_t::tx_running.
Referenced by app_do_connect().
thread_stats()
void * thread_stats (void * arg)
Statistics-thread entry point.
Parameters
arg Unused.
Returns
NULL.
Definition at line 240 of file threads.c.
References app_state_t::bitrate, app_state_t::bus_load, app_state_t::connected, g_app, idle_update_stats(), app_state_t::period_bits, and app_state_t::stats_running.
Referenced by app_do_connect().
app_do_connect()
void app_do_connect (void)
Open the interface in g_app and start the worker threads.
< Operation succeeded.
< Error-active bus state.
Definition at line 274 of file threads.c.
References app_state_t::bit_timing, app_state_t::bitrate, app_state_t::bus_load, app_state_t::bus_state, CAN_BUS_ACTIVE, app_state_t::connected, app_state_t::data_bitrate, drv_can_error_string(), drv_can_get_socketcan(), drv_can_init(), DRV_CAN_OK, app_state_t::error_count, app_state_t::fd_mode, g_app, g_gui, gui_show_error(), gui_status_message(), gui_tx_panel_update_fd(), app_state_t::iface, app_state_t::listen_only, app_state_t::msg_seq, app_state_t::period_bits, app_state_t::rx_count, app_state_t::rx_running, app_state_t::rx_thread, app_state_t::stats_running, app_state_t::stats_thread, thread_rx(), thread_stats(), thread_tx(), gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, app_state_t::tx_count, app_state_t::tx_running, app_state_t::tx_thread, and gui_widgets_t::window.
Referenced by gui_show_settings_dialog().
app_do_disconnect()
void app_do_disconnect (void)
Stop the worker threads and close the interface.
Definition at line 337 of file threads.c.
References app_state_t::connected, drv_can_deinit(), g_app, g_gui, gui_status_message(), gui_update_stats(), app_state_t::iface, app_state_t::rx_running, app_state_t::rx_thread, app_state_t::shutting_down, app_state_t::stats_running, app_state_t::stats_thread, gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, gui_widgets_t::toolbar_trace_start, gui_widgets_t::toolbar_trace_stop, app_state_t::tracing, app_state_t::tx_running, and app_state_t::tx_thread.
Referenced by app_state_cleanup(), gui_show_settings_dialog(), on_disconnect(), on_quit(), and on_window_delete().
Variable Documentation
g_gui
gui_widgets_t g_gui extern
The process-wide GUI widget registry (defined in threads.c).
The process-wide GUI widget registry (defined in threads.c).
Definition at line 38 of file threads.c.
Referenced by app_do_connect(), app_do_disconnect(), app_state_init(), build_stats_bar(), build_toolbar(), create_stats_panel(), create_trace_view(), gui_add_message(), gui_clear_trace(), gui_create_main_window(), gui_create_signal_view(), gui_refresh_trace_display(), gui_show_transmit_window(), gui_signal_decode_message(), gui_status_message(), gui_update_stats(), idle_add_message(), idle_update_stats(), on_about(), on_connect(), on_db_load(), on_load_dbc(), on_quit(), on_settings(), on_trace_save(), on_trace_start(), on_trace_stop(), sig_table_rebuild(), and sig_update_dbc_label().