PCAN-View Linux: gui/main_window.c File Reference
main_window.c File Reference
Main GTK3 window: menu bar, statistics bar, toolbar, trace, TX panel.
#include <stdio.h>
#include <string.h>
#include <stdlib.h>
#include <errno.h>
#include <ctype.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/app_state.h"
#include "../inc/can_message.h"
#include "../inc/version.h"
Data Structures
struct tx_panel_row_t
Macros
#define TX_PANEL_DATA_COLS CANFD_DATA_MAX /* up to 64 byte fields for CAN FD */
#define TX_PANEL_MAX_ROWS 16
#define TX_STD_ID_MAX 0x7FFu
#define TX_EXT_ID_MAX 0x1FFFFFFFu
#define TX_BYTE_MAX 0xFFu
Enumerations
enum {
TXG_COL_NUM = 0 , TXG_COL_ID , TXG_COL_EXT , TXG_COL_RTR ,
TXG_COL_DLC , TXG_COL_DATA , TXG_COL_INTERVAL , TXG_COL_SEND ,
TXG_COL_START , TXG_COL_STOP , TXG_COL_STATUS
}
Functions
GtkWidget * create_trace_view (void)
Trace view factory implemented in message_view.c.
static const char * find_asset_path (const char *name)
Resolve a bundled asset file across dev and installed layouts.
static GdkPixbuf * gui_load_logo (int size)
Load the Taksys logo scaled into a square of size px.
static tx_panel_row_t * txp_row_from_data (gpointer data)
Map a row-index pointer to its transmit-row struct.
static void txp_set_status (tx_panel_row_t *row, const char *color, const char *msg)
static void txp_clear_row (tx_panel_row_t *row)
Reset one transmit row to defaults.
static void txp_clear_all (void)
Reset every transmit row to defaults.
static void txp_add_row (void)
Append a new transmit row to the panel grid.
static void txp_remove_last_row (void)
Remove and destroy the last transmit row.
static void txp_set_error (tx_panel_row_t *row, const char *msg)
Show a red error status on a row.
static void txp_update_data_fields (tx_panel_row_t *row)
Show exactly DLC data-byte fields for a row (none if RTR).
static gboolean txp_build_frame (tx_panel_row_t *row, can_msg_t *msg)
Validate a transmit row and assemble a frame.
static gboolean txp_queue_frame (int row_index, gboolean cyclic)
Build and enqueue a row's frame for transmission.
static void txp_stop_cyclic_row (tx_panel_row_t *row, const char *status)
Stop a row's cyclic timer and update its buttons.
static void txp_stop_all_cyclic (void)
Stop cyclic transmission on every row.
static gboolean txp_cyclic_tick (gpointer data)
Cyclic-timer callback for one row.
static void txp_send_once (GtkWidget *w, gpointer d)
"Send" button handler for a row.
static void txp_start_cyclic (GtkWidget *w, gpointer d)
"Start" button handler — arm a row's cyclic timer.
static void txp_stop_cyclic (GtkWidget *w, gpointer d)
"Stop" button handler — disarm a row's cyclic timer.
static void txp_dlc_changed (GtkSpinButton *btn, gpointer d)
DLC spin handler — refresh visible data fields.
static void txp_rtr_toggled (GtkToggleButton *btn, gpointer d)
RTR toggle handler — refresh visible data fields.
static gboolean on_window_delete (GtkWidget *w, GdkEvent *e, gpointer d)
Window delete-event: stop cyclic TX and disconnect before destroy.
static void on_connect (GtkWidget *w, gpointer d)
Connect action — open the settings/connect dialog.
static void on_disconnect (GtkWidget *w, gpointer d)
Disconnect action — stop cyclic TX and disconnect.
static void on_clear (GtkWidget *w, gpointer d)
Clear-trace action.
static void on_trace_start (GtkWidget *w, gpointer d)
Trace > Start — begin capturing every Rx/Tx frame in memory.
static void on_trace_stop (GtkWidget *w, gpointer d)
Trace > Stop — halt capture (buffer retained for export).
static void trace_csv_write_row (FILE *fp, const can_msg_t *msg)
Write one captured frame as a CSV record.
static void on_trace_save (GtkWidget *w, gpointer d)
Trace > Save as CSV — export the captured buffer to a file.
static void on_transmit (GtkWidget *w, gpointer d)
Open the advanced transmit window.
static void on_settings (GtkWidget *w, gpointer d)
Open the connection-settings dialog.
static void on_about (GtkWidget *w, gpointer d)
Open the About dialog.
static void on_quit (GtkWidget *w, gpointer d)
Quit action — tear down and destroy the main window.
static void on_dedup_toggle (GtkCheckMenuItem *item, gpointer d)
View > Roll Up Tx — toggle TX deduplication.
static void on_id_format_toggle (GtkCheckMenuItem *item, gpointer d)
View > ID Format — switch ID display radix.
static void on_data_format_toggle (GtkCheckMenuItem *item, gpointer d)
View > Data Format — switch payload display format.
static GtkWidget * menu_item (const char *label, GCallback cb, gpointer data)
Create a mnemonic menu item wired to a callback.
static GtkWidget * stats_bar_field (GtkWidget *bar, const char *caption, const char *initial)
Add one "caption: value" cell to the statistics bar.
static void stats_bar_separator (GtkWidget *bar)
Append a vertical separator to the statistics bar.
static GtkWidget * build_stats_bar (void)
Build the statistics bar shown directly below the menu bar.
static GtkWidget * build_menubar (void)
Build the application menu bar.
static GtkWidget * make_toolbtn (const char *icon, const char *tooltip, GCallback cb)
Create an icon tool button.
static GtkWidget * build_toolbar (void)
Build the main toolbar.
static gboolean on_key_press (GtkWidget *w, GdkEventKey *ev, gpointer d)
Global key handler (F5 connect, F6 disconnect, Ctrl+Del clear).
static int parse_hex_u32_strict (const char *s, uint32_t max, uint32_t *out)
Strictly parse a bounded hex value.
static uint8_t canfd_round_len (int n)
Round a byte count up to a valid CAN FD payload length.
static GtkWidget * txp_header_label (const char *text)
Create a centred transmit-panel header label.
static GtkWidget * create_transmit_panel (void)
Build the inline transmit panel (header + first row).
void gui_tx_panel_update_fd (void)
Sync the transmit panel with the current CAN FD link mode.
GtkWidget * gui_create_main_window (GtkApplication *app)
Build the main application window and all of its widgets.
void gui_show_about_dialog (GtkWidget *parent)
Show the About dialog (Taksys branding).
Variables
struct {
tx_panel_row_t rows [16]
int count
GtkWidget * rows_box
GtkWidget * placeholder
} s_txp
Detailed Description
Main GTK3 window: menu bar, statistics bar, toolbar, trace, TX panel.
Constructs and owns the entire main-window UI and most of its behaviour:
the menu bar (File, Trace, CAN, View, Help),
the always-visible statistics bar below the menu,
the toolbar,
a vertical paned area with the receive trace on top and the inline transmit panel below,
the Trace capture menu (Start/Stop/Save as CSV),
the inline transmit panel with per-row CAN FD DLC up to 64 and dynamic, wrapping data-byte fields,
Taksys branding (window icon, footer, About dialog).
Window layout:
*   GtkApplicationWindow
*   └─ GtkBox (vertical)
*      ├─ GtkMenuBar
*      ├─ statistics bar  (GtkBox)
*      ├─ GtkToolbar
*      ├─ GtkPaned (vertical)
*      │  ├─ trace view   (scrolled GtkTreeView)
*      │  └─ transmit panel (scrolled GtkGrid + per-row GtkFlowBox)
*      ├─ GtkStatusbar
*      └─ footer  (Taksys logo + credits)
*
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file main_window.c.
Macro Definition Documentation
TX_PANEL_DATA_COLS
#define TX_PANEL_DATA_COLS CANFD_DATA_MAX /* up to 64 byte fields for CAN FD */
Definition at line 124 of file main_window.c.
TX_PANEL_MAX_ROWS
#define TX_PANEL_MAX_ROWS 16
Definition at line 125 of file main_window.c.
TX_STD_ID_MAX
#define TX_STD_ID_MAX 0x7FFu
Definition at line 126 of file main_window.c.
TX_EXT_ID_MAX
#define TX_EXT_ID_MAX 0x1FFFFFFFu
Definition at line 127 of file main_window.c.
TX_BYTE_MAX
#define TX_BYTE_MAX 0xFFu
Definition at line 128 of file main_window.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Enumerator
TXG_COL_NUM
TXG_COL_ID
TXG_COL_EXT
TXG_COL_RTR
TXG_COL_DLC
TXG_COL_DATA
TXG_COL_INTERVAL
TXG_COL_SEND
TXG_COL_START
TXG_COL_STOP
TXG_COL_STATUS
Definition at line 134 of file main_window.c.
Function Documentation
create_trace_view()
GtkWidget * create_trace_view (void) extern
Trace view factory implemented in message_view.c.
Returns
Scrolled tree view.
Trace view factory implemented in message_view.c.
Returns
A scrolled-window container holding the tree view.
Definition at line 242 of file message_view.c.
References g_gui, TCOL_COUNT, TCOL_DATA, TCOL_DIR, TCOL_DLC, TCOL_FG, TCOL_FREQ, TCOL_ID, TCOL_ID_RAW, TCOL_INTERVAL, TCOL_NUM, TCOL_SEQ, TCOL_TIME, TCOL_TYPE, gui_widgets_t::trace_store, and gui_widgets_t::trace_view.
Referenced by gui_create_main_window().
find_asset_path()
static const char * find_asset_path (const char * name) static
Resolve a bundled asset file across dev and installed layouts.
Searches, in order: $PCAN_VIEW_ASSET_DIR, paths relative to the executable (dev assets/ and installed ../share/pcan-view), and the system share dirs.
Parameters
name Asset filename (e.g. "taksys_logo.png").
Returns
Static path string valid until the next call, or NULL if not found.
Definition at line 65 of file main_window.c.
Referenced by gui_load_logo().
gui_load_logo()
static GdkPixbuf * gui_load_logo (int size) static
Load the Taksys logo scaled into a square of size px.
Parameters
size Target edge length in pixels.
Returns
A new GdkPixbuf (caller unrefs) or NULL if unavailable.
Definition at line 110 of file main_window.c.
References find_asset_path().
Referenced by gui_create_main_window(), and gui_show_about_dialog().
txp_row_from_data()
static tx_panel_row_t * txp_row_from_data (gpointer data) static
Map a row-index pointer to its transmit-row struct.
Parameters
data Row index as pointer.
Returns
Row pointer or NULL.
Definition at line 817 of file main_window.c.
References s_txp, and TX_PANEL_MAX_ROWS.
Referenced by txp_cyclic_tick(), txp_dlc_changed(), txp_queue_frame(), txp_rtr_toggled(), txp_start_cyclic(), and txp_stop_cyclic().
txp_set_status()
static void txp_set_status (tx_panel_row_t * row, const char * color, const char * msg) static
Definition at line 825 of file main_window.c.
References tx_panel_row_t::status_lbl.
Referenced by txp_queue_frame(), txp_set_error(), txp_start_cyclic(), and txp_stop_cyclic_row().
txp_clear_row()
static void txp_clear_row (tx_panel_row_t * row) static
Reset one transmit row to defaults.
Parameters
row Row.
< Maximum payload of a CAN FD frame.
Definition at line 846 of file main_window.c.
References tx_panel_row_t::data_entry, tx_panel_row_t::dlc_spin, tx_panel_row_t::ext_check, tx_panel_row_t::id_entry, tx_panel_row_t::interval_spin, tx_panel_row_t::rtr_check, TX_PANEL_DATA_COLS, and txp_stop_cyclic_row().
Referenced by txp_clear_all().
txp_clear_all()
static void txp_clear_all (void) static
Reset every transmit row to defaults.
Definition at line 864 of file main_window.c.
References s_txp, and txp_clear_row().
Referenced by create_transmit_panel().
txp_add_row()
static void txp_add_row (void) static
Append a new transmit row to the panel grid.
< Maximum payload of a CAN FD frame.
< Maximum payload of a classic CAN frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 873 of file main_window.c.
References CAN_MAX_DLC, CANFD_DATA_MAX, tx_panel_row_t::data_box, tx_panel_row_t::data_entry, tx_panel_row_t::dlc_spin, tx_panel_row_t::ext_check, app_state_t::fd_mode, g_app, tx_panel_row_t::id_entry, tx_panel_row_t::interval_spin, tx_panel_row_t::num_lbl, tx_panel_row_t::rtr_check, s_txp, tx_panel_row_t::send_btn, tx_panel_row_t::start_btn, tx_panel_row_t::status_lbl, tx_panel_row_t::stop_btn, TX_PANEL_DATA_COLS, TX_PANEL_MAX_ROWS, TXG_COL_DATA, TXG_COL_DLC, TXG_COL_EXT, TXG_COL_ID, TXG_COL_INTERVAL, TXG_COL_NUM, TXG_COL_RTR, TXG_COL_SEND, TXG_COL_START, TXG_COL_STATUS, TXG_COL_STOP, txp_dlc_changed(), txp_rtr_toggled(), txp_send_once(), txp_start_cyclic(), txp_stop_cyclic(), and txp_update_data_fields().
Referenced by create_transmit_panel().
txp_remove_last_row()
static void txp_remove_last_row (void) static
Remove and destroy the last transmit row.
Definition at line 983 of file main_window.c.
References tx_panel_row_t::cyclic_id, tx_panel_row_t::data_box, tx_panel_row_t::dlc_spin, tx_panel_row_t::ext_check, tx_panel_row_t::id_entry, tx_panel_row_t::interval_spin, tx_panel_row_t::num_lbl, tx_panel_row_t::rtr_check, s_txp, tx_panel_row_t::send_btn, tx_panel_row_t::start_btn, tx_panel_row_t::status_lbl, and tx_panel_row_t::stop_btn.
Referenced by create_transmit_panel().
txp_set_error()
static void txp_set_error (tx_panel_row_t * row, const char * msg) static
Show a red error status on a row.
Parameters
row Row.
msg Message.
Definition at line 1007 of file main_window.c.
References txp_set_status().
Referenced by txp_build_frame(), txp_queue_frame(), and txp_start_cyclic().
txp_update_data_fields()
static void txp_update_data_fields (tx_panel_row_t * row) static
Show exactly DLC data-byte fields for a row (none if RTR).
Parameters
row Row.
< Maximum payload of a CAN FD frame.
Definition at line 1015 of file main_window.c.
References tx_panel_row_t::data_entry, tx_panel_row_t::dlc_spin, tx_panel_row_t::rtr_check, and TX_PANEL_DATA_COLS.
Referenced by gui_tx_panel_update_fd(), txp_add_row(), txp_dlc_changed(), and txp_rtr_toggled().
txp_build_frame()
static gboolean txp_build_frame (tx_panel_row_t * row, can_msg_t * msg) static
Validate a transmit row and assemble a frame.
Parameters
row Row.
msg Output frame.
Returns
TRUE if valid.
< Maximum payload of a classic CAN frame.
< Maximum payload of a classic CAN frame.
< Maximum payload of a CAN FD frame.
Definition at line 1060 of file main_window.c.
References CAN_MAX_DLC, canfd_round_len(), can_msg_t::data, tx_panel_row_t::data_entry, can_msg_t::dlc, tx_panel_row_t::dlc_spin, tx_panel_row_t::ext_check, app_state_t::fd_mode, g_app, can_msg_t::id, tx_panel_row_t::id_entry, can_msg_t::is_brs, can_msg_t::is_extended, can_msg_t::is_fd, can_msg_t::is_remote, parse_hex_u32_strict(), tx_panel_row_t::rtr_check, TX_BYTE_MAX, TX_EXT_ID_MAX, TX_PANEL_DATA_COLS, TX_STD_ID_MAX, txp_set_error(), and value.
Referenced by txp_queue_frame(), and txp_start_cyclic().
txp_queue_frame()
static gboolean txp_queue_frame (int row_index, gboolean cyclic) static
Build and enqueue a row's frame for transmission.
Parameters
row_index Row.
cyclic Non-zero if from the cyclic timer.
Returns
TRUE on success.
Definition at line 1115 of file main_window.c.
References app_state_t::connected, g_app, app_state_t::tx_queue, txp_build_frame(), txp_row_from_data(), txp_set_error(), and txp_set_status().
Referenced by txp_cyclic_tick(), txp_send_once(), and txp_start_cyclic().
txp_stop_cyclic_row()
static void txp_stop_cyclic_row (tx_panel_row_t * row, const char * status) static
Stop a row's cyclic timer and update its buttons.
Parameters
row Row.
status Status text.
Definition at line 1146 of file main_window.c.
References tx_panel_row_t::cyclic_id, tx_panel_row_t::start_btn, tx_panel_row_t::stop_btn, and txp_set_status().
Referenced by txp_clear_row(), txp_cyclic_tick(), txp_stop_all_cyclic(), and txp_stop_cyclic().
txp_stop_all_cyclic()
static void txp_stop_all_cyclic (void) static
Stop cyclic transmission on every row.
Definition at line 1166 of file main_window.c.
References s_txp, TX_PANEL_MAX_ROWS, and txp_stop_cyclic_row().
Referenced by on_disconnect(), on_quit(), and on_window_delete().
txp_cyclic_tick()
static gboolean txp_cyclic_tick (gpointer data) static
Cyclic-timer callback for one row.
Parameters
data Row index.
Returns
Continue/remove.
Definition at line 1175 of file main_window.c.
References app_state_t::connected, tx_panel_row_t::cyclic_id, g_app, txp_queue_frame(), txp_row_from_data(), and txp_stop_cyclic_row().
Referenced by txp_start_cyclic().
txp_send_once()
static void txp_send_once (GtkWidget * w, gpointer d) static
"Send" button handler for a row.
Parameters
w Widget.
d Row index.
Definition at line 1194 of file main_window.c.
References txp_queue_frame().
Referenced by txp_add_row().
txp_start_cyclic()
static void txp_start_cyclic (GtkWidget * w, gpointer d) static
"Start" button handler — arm a row's cyclic timer.
Parameters
w Widget.
d Row index.
Definition at line 1203 of file main_window.c.
References app_state_t::connected, tx_panel_row_t::cyclic_id, g_app, tx_panel_row_t::interval_spin, tx_panel_row_t::start_btn, tx_panel_row_t::stop_btn, txp_build_frame(), txp_cyclic_tick(), txp_queue_frame(), txp_row_from_data(), txp_set_error(), and txp_set_status().
Referenced by txp_add_row().
txp_stop_cyclic()
static void txp_stop_cyclic (GtkWidget * w, gpointer d) static
"Stop" button handler — disarm a row's cyclic timer.
Parameters
w Widget.
d Row index.
Definition at line 1236 of file main_window.c.
References txp_row_from_data(), and txp_stop_cyclic_row().
Referenced by txp_add_row().
txp_dlc_changed()
static void txp_dlc_changed (GtkSpinButton * btn, gpointer d) static
DLC spin handler — refresh visible data fields.
Parameters
btn Spin.
d Row index.
Definition at line 1246 of file main_window.c.
References txp_row_from_data(), and txp_update_data_fields().
Referenced by txp_add_row().
txp_rtr_toggled()
static void txp_rtr_toggled (GtkToggleButton * btn, gpointer d) static
RTR toggle handler — refresh visible data fields.
Parameters
btn Button.
d Row index.
Definition at line 1255 of file main_window.c.
References txp_row_from_data(), and txp_update_data_fields().
Referenced by txp_add_row().
on_window_delete()
static gboolean on_window_delete (GtkWidget * w, GdkEvent * e, gpointer d) static
Window delete-event: stop cyclic TX and disconnect before destroy.
Parameters
w Window.
e Event.
d Unused.
Returns
FALSE (allow destroy).
Definition at line 200 of file main_window.c.
References app_do_disconnect(), and txp_stop_all_cyclic().
Referenced by gui_create_main_window().
on_connect()
static void on_connect (GtkWidget * w, gpointer d) static
Connect action — open the settings/connect dialog.
Definition at line 212 of file main_window.c.
References g_gui, gui_show_settings_dialog(), and gui_widgets_t::window.
Referenced by build_menubar(), build_toolbar(), and on_key_press().
on_disconnect()
static void on_disconnect (GtkWidget * w, gpointer d) static
Disconnect action — stop cyclic TX and disconnect.
Definition at line 221 of file main_window.c.
References app_do_disconnect(), and txp_stop_all_cyclic().
Referenced by build_menubar(), build_toolbar(), and on_key_press().
on_clear()
static void on_clear (GtkWidget * w, gpointer d) static
Clear-trace action.
Definition at line 231 of file main_window.c.
References gui_clear_trace(), and gui_status_message().
Referenced by build_menubar(), build_toolbar(), and on_key_press().
on_trace_start()
static void on_trace_start (GtkWidget * w, gpointer d) static
Trace > Start — begin capturing every Rx/Tx frame in memory.
on_trace_stop halts capture (the buffer is retained); on_trace_save writes the captured frames to a CSV file.
Definition at line 244 of file main_window.c.
References app_state_t::connected, g_app, g_gui, gui_show_error(), gui_status_message(), gui_widgets_t::toolbar_trace_start, gui_widgets_t::toolbar_trace_stop, app_state_t::trace_len, app_state_t::trace_mutex, app_state_t::tracing, and gui_widgets_t::window.
Referenced by build_menubar(), and build_toolbar().
on_trace_stop()
static void on_trace_stop (GtkWidget * w, gpointer d) static
Trace > Stop — halt capture (buffer retained for export).
Definition at line 267 of file main_window.c.
References g_app, g_gui, gui_status_message(), gui_widgets_t::toolbar_trace_start, gui_widgets_t::toolbar_trace_stop, app_state_t::trace_len, and app_state_t::tracing.
Referenced by build_menubar(), and build_toolbar().
trace_csv_write_row()
static void trace_csv_write_row (FILE * fp, const can_msg_t * msg) static
Write one captured frame as a CSV record.
Parameters
fp Open output file.
msg Frame to serialise.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Frame direction: transmitted.
Definition at line 285 of file main_window.c.
References CAN_DIR_TX, CANFD_DATA_MAX, can_msg_t::data, can_msg_t::direction, can_msg_t::dlc, gui_msg_type_str(), can_msg_t::id, can_msg_t::is_extended, can_msg_t::seq, and can_msg_t::timestamp.
Referenced by on_trace_save().
on_trace_save()
static void on_trace_save (GtkWidget * w, gpointer d) static
Trace > Save as CSV — export the captured buffer to a file.
< Max trace-file path length.
< Max trace-file path length.
Definition at line 322 of file main_window.c.
References APP_TRACE_FILE_LEN, g_app, g_gui, gui_show_error(), gui_status_message(), app_state_t::trace_buf, trace_csv_write_row(), app_state_t::trace_filename, app_state_t::trace_len, app_state_t::trace_mutex, and gui_widgets_t::window.
Referenced by build_menubar().
on_transmit()
static void on_transmit (GtkWidget * w, gpointer d) static
Open the advanced transmit window.
Definition at line 377 of file main_window.c.
References gui_show_transmit_window().
Referenced by build_menubar(), build_toolbar(), and create_transmit_panel().
on_settings()
static void on_settings (GtkWidget * w, gpointer d) static
Open the connection-settings dialog.
Definition at line 386 of file main_window.c.
References g_gui, gui_show_settings_dialog(), and gui_widgets_t::window.
Referenced by build_menubar(), and build_toolbar().
on_about()
static void on_about (GtkWidget * w, gpointer d) static
Open the About dialog.
Definition at line 395 of file main_window.c.
References g_gui, gui_show_about_dialog(), and gui_widgets_t::window.
Referenced by build_menubar().
on_quit()
static void on_quit (GtkWidget * w, gpointer d) static
Quit action — tear down and destroy the main window.
Definition at line 404 of file main_window.c.
References app_do_disconnect(), g_gui, txp_stop_all_cyclic(), and gui_widgets_t::window.
Referenced by build_menubar().
on_dedup_toggle()
static void on_dedup_toggle (GtkCheckMenuItem * item, gpointer d) static
View > Roll Up Tx — toggle TX deduplication.
Definition at line 415 of file main_window.c.
References app_state_t::dedup_mode, g_app, gui_clear_trace(), and gui_status_message().
Referenced by build_menubar().
on_id_format_toggle()
static void on_id_format_toggle (GtkCheckMenuItem * item, gpointer d) static
View > ID Format — switch ID display radix.
Definition at line 427 of file main_window.c.
References APP_ID_FORMAT_DEC, g_app, gui_refresh_trace_display(), gui_status_message(), and app_state_t::id_format.
Referenced by build_menubar().
on_data_format_toggle()
static void on_data_format_toggle (GtkCheckMenuItem * item, gpointer d) static
View > Data Format — switch payload display format.
Definition at line 442 of file main_window.c.
References APP_DATA_FORMAT_ASCII, APP_DATA_FORMAT_DEC, app_state_t::data_format, g_app, gui_refresh_trace_display(), and gui_status_message().
Referenced by build_menubar().
menu_item()
static GtkWidget * menu_item (const char * label, GCallback cb, gpointer data) static
Create a mnemonic menu item wired to a callback.
Parameters
label Mnemonic label.
cb Activate callback.
data User data.
Returns
The menu item.
Definition at line 464 of file main_window.c.
References label.
Referenced by build_menubar().
stats_bar_field()
static GtkWidget * stats_bar_field (GtkWidget * bar, const char * caption, const char * initial) static
Add one "caption: value" cell to the statistics bar.
Parameters
bar The statistics bar box.
caption Bold caption text.
initial Initial value text.
Returns
The value label, so gui_update_stats can refresh it.
Definition at line 479 of file main_window.c.
Referenced by build_stats_bar().
stats_bar_separator()
static void stats_bar_separator (GtkWidget * bar) static
Append a vertical separator to the statistics bar.
Parameters
bar Bar box.
Definition at line 503 of file main_window.c.
Referenced by build_stats_bar().
build_stats_bar()
static GtkWidget * build_stats_bar (void) static
Build the statistics bar shown directly below the menu bar.
Returns
The populated bar widget.
Definition at line 514 of file main_window.c.
References g_gui, gui_widgets_t::lbl_bitrate, gui_widgets_t::lbl_bus_state, gui_widgets_t::lbl_connection, gui_widgets_t::lbl_err, gui_widgets_t::lbl_rx, gui_widgets_t::lbl_tx, gui_widgets_t::progress_bus_load, stats_bar_field(), and stats_bar_separator().
Referenced by gui_create_main_window().
build_menubar()
static GtkWidget * build_menubar (void) static
Build the application menu bar.
Returns
The menu bar widget.
Definition at line 557 of file main_window.c.
References APP_DATA_FORMAT_ASCII, APP_DATA_FORMAT_DEC, APP_DATA_FORMAT_HEX, APP_ID_FORMAT_DEC, APP_ID_FORMAT_HEX, app_state_t::data_format, g_app, app_state_t::id_format, menu_item(), on_about(), on_clear(), on_connect(), on_data_format_toggle(), on_dedup_toggle(), on_disconnect(), on_id_format_toggle(), on_quit(), on_settings(), on_trace_save(), on_trace_start(), on_trace_stop(), and on_transmit().
Referenced by gui_create_main_window().
make_toolbtn()
static GtkWidget * make_toolbtn (const char * icon, const char * tooltip, GCallback cb) static
Create an icon tool button.
Parameters
icon Icon name.
tooltip Tooltip.
cb Click callback.
Returns
The tool item as a widget.
Definition at line 694 of file main_window.c.
Referenced by build_toolbar().
build_toolbar()
static GtkWidget * build_toolbar (void) static
Build the main toolbar.
Returns
The toolbar widget.
Definition at line 708 of file main_window.c.
References g_gui, make_toolbtn(), on_clear(), on_connect(), on_disconnect(), on_settings(), on_trace_start(), on_trace_stop(), on_transmit(), gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, gui_widgets_t::toolbar_trace_start, and gui_widgets_t::toolbar_trace_stop.
Referenced by gui_create_main_window().
on_key_press()
static gboolean on_key_press (GtkWidget * w, GdkEventKey * ev, gpointer d) static
Global key handler (F5 connect, F6 disconnect, Ctrl+Del clear).
Parameters
w Widget.
ev Key event.
d Unused.
Returns
TRUE if handled.
Definition at line 769 of file main_window.c.
References on_clear(), on_connect(), and on_disconnect().
Referenced by gui_create_main_window().
parse_hex_u32_strict()
static int parse_hex_u32_strict (const char * s, uint32_t max, uint32_t * out) static
Strictly parse a bounded hex value.
Parameters
s Text.
max Max value.
out Result.
Returns
0 ok, -1 error.
Definition at line 794 of file main_window.c.
Referenced by txp_build_frame().
canfd_round_len()
static uint8_t canfd_round_len (int n) static
Round a byte count up to a valid CAN FD payload length.
CAN FD frames only carry specific lengths (0..8, 12, 16, 20, 24, 32, 48, 64).
Parameters
n Requested length.
Returns
The smallest valid CAN FD length >= n (capped at 64).
< Maximum payload of a CAN FD frame.
Definition at line 1045 of file main_window.c.
References CANFD_DATA_MAX.
Referenced by txp_build_frame().
txp_header_label()
static GtkWidget * txp_header_label (const char * text) static
Create a centred transmit-panel header label.
Parameters
text Text.
Returns
The label.
Definition at line 1264 of file main_window.c.
References label.
Referenced by create_transmit_panel().
create_transmit_panel()
static GtkWidget * create_transmit_panel (void) static
Build the inline transmit panel (header + first row).
Returns
The panel frame.
Definition at line 1276 of file main_window.c.
References gui_tx_panel_update_fd(), on_transmit(), s_txp, TXG_COL_DATA, TXG_COL_DLC, TXG_COL_EXT, TXG_COL_ID, TXG_COL_INTERVAL, TXG_COL_NUM, TXG_COL_RTR, TXG_COL_STATUS, txp_add_row(), txp_clear_all(), txp_header_label(), and txp_remove_last_row().
Referenced by gui_create_main_window().
gui_tx_panel_update_fd()
void gui_tx_panel_update_fd (void)
Sync the transmit panel with the current CAN FD link mode.
Widens each row's DLC range to 64 in CAN FD mode (8 in classic) and refreshes the number of visible data-byte fields.
< Maximum payload of a CAN FD frame.
< Maximum payload of a classic CAN frame.
Definition at line 1358 of file main_window.c.
References CAN_MAX_DLC, CANFD_DATA_MAX, tx_panel_row_t::dlc_spin, app_state_t::fd_mode, g_app, s_txp, and txp_update_data_fields().
Referenced by app_do_connect(), and create_transmit_panel().
gui_create_main_window()
GtkWidget * gui_create_main_window (GtkApplication * app)
Build the main application window and all of its widgets.
Parameters
app The owning GtkApplication.
Returns
The newly created top-level window.
Definition at line 1379 of file main_window.c.
References build_menubar(), build_stats_bar(), build_toolbar(), create_trace_view(), create_transmit_panel(), g_gui, gui_load_logo(), gui_update_stats(), on_key_press(), on_window_delete(), gui_widgets_t::statusbar, gui_widgets_t::statusbar_ctx, and gui_widgets_t::window.
Referenced by on_app_activate().
gui_show_about_dialog()
void gui_show_about_dialog (GtkWidget * parent)
Show the About dialog (Taksys branding).
Parameters
parent Transient parent.
Definition at line 1483 of file main_window.c.
References gui_load_logo(), PCAN_VIEW_APP_NAME, PCAN_VIEW_COPYRIGHT, PCAN_VIEW_VENDOR, and PCAN_VIEW_VERSION.
Referenced by on_about().
Variable Documentation
rows
tx_panel_row_t rows[16]
Definition at line 165 of file main_window.c.
count
int count
Definition at line 166 of file main_window.c.
Referenced by parse_raw_data(), and socketcan_list_interfaces().
rows_box
GtkWidget* rows_box
Definition at line 167 of file main_window.c.
placeholder
GtkWidget* placeholder
Definition at line 168 of file main_window.c.
[struct]
struct { ... } s_txp
Referenced by create_transmit_panel(), gui_tx_panel_update_fd(), txp_add_row(), txp_clear_all(), txp_remove_last_row(), txp_row_from_data(), and txp_stop_all_cyclic().