PCAN-View Linux: gui/message_view.c File Reference
message_view.c File Reference
CAN trace GtkTreeView, value formatting, and statistics rendering.
#include <stdio.h>
#include <string.h>
#include <stdarg.h>
#include <time.h>
#include <ctype.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/app_state.h"
#include "../inc/can_message.h"
Macros
#define MAX_TRACE_ROWS 50000
#define DEDUP_TABLE_SZ 0x800u /* initial hash table size */
#define DATA_TEXT_MAX 512
#define RAW_DATA_MAX ((CANFD_DATA_MAX * 2u) + 1u)
#define ID_TEXT_MAX 16
#define TIME_TEXT_MAX 32
#define INTERVAL_TEXT_MAX 32
#define FREQ_TEXT_MAX 32
#define ADD_ROW(lbl_str, widget)
Functions
void gui_format_id (char *buf, size_t sz, uint32_t id, int is_ext)
Format a CAN identifier into buf per the active display radix.
void gui_format_data (char *buf, size_t sz, const uint8_t *d, uint8_t dlc)
Format payload bytes into buf per the active data format.
static void format_raw_data (char *buf, size_t sz, const uint8_t *d, uint8_t dlc)
Format payload bytes as a compact uppercase hex string (no spaces).
static int hex_value (char c)
Convert a hex digit to its value, or -1 if not a hex digit.
static uint8_t parse_raw_data (const char *raw, uint8_t *out, uint8_t dlc)
Parse a compact hex string back into bytes.
static gint64 timespec_to_ns (const struct timespec *ts)
Convert a timespec to nanoseconds.
static void format_timestamp (char *buf, size_t sz, const struct timespec *ts)
Render a timespec as HH:MM:SS.mmm.
static void format_interval (char *buf, size_t sz, gint64 delta_ns)
Render an inter-frame interval in milliseconds.
static void format_frequency (char *buf, size_t sz, gint64 delta_ns)
Render a frame frequency in hertz from an interval.
static gboolean should_rollup_message (const can_msg_t *msg)
Decide whether msg should roll up onto an existing row.
const char * gui_msg_type_str (const can_msg_t *m)
Return a short frame-type label ("Std", "Ext", "FD+BRS", …).
const char * gui_bus_state_str (uint8_t st)
Return a bus-state label for a CAN_BUS_* value.
const char * gui_bus_state_color (uint8_t st)
Return a Pango colour name for a CAN_BUS_* value.
static const char * row_fg (const can_msg_t *m)
Return the row foreground colour for a frame, or NULL for default.
GtkWidget * create_trace_view (void)
Create the trace GtkTreeView and its backing GtkListStore.
GtkWidget * create_stats_panel (void)
Create a vertical statistics panel (legacy/optional layout).
void gui_add_message (const can_msg_t *msg)
Append (or roll up) one frame into the trace view.
void gui_clear_trace (void)
Remove every row from the trace view.
void gui_refresh_trace_display (void)
Re-render existing trace rows after a display-format change.
void gui_update_stats (void)
Refresh the statistics bar from g_app counters.
void gui_status_message (const char *fmt,...)
Set the status-bar text (printf-style).
void gui_show_error (GtkWidget *parent, const char *title, const char *msg)
Show a modal error dialog.
Detailed Description
CAN trace GtkTreeView, value formatting, and statistics rendering.
Builds and maintains the receive/transmit trace list and its backing GtkListStore, including row roll-up (deduplication) by CAN ID, interval and frequency computation, and re-formatting when the ID/data display mode changes. Also provides the shared value-formatting helpers (gui_format_id, gui_format_data, gui_msg_type_str, …), the statistics refresh (gui_update_stats), the status-bar helper, and the modal error dialog.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file message_view.c.
Macro Definition Documentation
MAX_TRACE_ROWS
#define MAX_TRACE_ROWS 50000
Definition at line 31 of file message_view.c.
DEDUP_TABLE_SZ
#define DEDUP_TABLE_SZ 0x800u /* initial hash table size */
Definition at line 32 of file message_view.c.
DATA_TEXT_MAX
#define DATA_TEXT_MAX 512
Definition at line 33 of file message_view.c.
RAW_DATA_MAX
#define RAW_DATA_MAX ((CANFD_DATA_MAX * 2u) + 1u)
Definition at line 34 of file message_view.c.
ID_TEXT_MAX
#define ID_TEXT_MAX 16
Definition at line 35 of file message_view.c.
TIME_TEXT_MAX
#define TIME_TEXT_MAX 32
Definition at line 36 of file message_view.c.
INTERVAL_TEXT_MAX
#define INTERVAL_TEXT_MAX 32
Definition at line 37 of file message_view.c.
FREQ_TEXT_MAX
#define FREQ_TEXT_MAX 32
Definition at line 38 of file message_view.c.
ADD_ROW
#define ADD_ROW (lbl_str, widget)
Value:
    do { \
    GtkWidget *_l = gtk_label_new(lbl_str); \
    gtk_label_set_xalign(GTK_LABEL(_l), 1.0f); \
    gtk_grid_attach(GTK_GRID(grid), _l, 0, row, 1, 1); \
    gtk_grid_attach(GTK_GRID(grid), (widget), 1, row, 1, 1); \
    row++; \
} while(0)
Function Documentation
gui_format_id()
void gui_format_id (char * buf, size_t sz, uint32_t id, int is_ext)
Format a CAN identifier into buf per the active display radix.
Parameters
buf Output buffer.
sz Buffer size.
id Identifier value.
is_ext Non-zero for an extended (29-bit) ID.
Definition at line 44 of file message_view.c.
References APP_ID_FORMAT_DEC, g_app, and app_state_t::id_format.
Referenced by gui_add_message(), and gui_refresh_trace_display().
gui_format_data()
void gui_format_data (char * buf, size_t sz, const uint8_t * d, uint8_t dlc)
Format payload bytes into buf per the active data format.
Parameters
buf Output buffer.
sz Buffer size.
d Payload bytes.
dlc Number of bytes.
Definition at line 57 of file message_view.c.
References APP_DATA_FORMAT_ASCII, APP_DATA_FORMAT_DEC, app_state_t::data_format, and g_app.
Referenced by gui_add_message(), and gui_refresh_trace_display().
format_raw_data()
static void format_raw_data (char * buf, size_t sz, const uint8_t * d, uint8_t dlc) static
Format payload bytes as a compact uppercase hex string (no spaces).
Parameters
buf Output buffer.
sz Size.
d Bytes.
dlc Count.
Definition at line 92 of file message_view.c.
Referenced by gui_add_message().
hex_value()
static int hex_value (char c) static
Convert a hex digit to its value, or -1 if not a hex digit.
Parameters
c Char.
Returns
0..15 or -1.
Definition at line 105 of file message_view.c.
Referenced by parse_raw_data().
parse_raw_data()
static uint8_t parse_raw_data (const char * raw, uint8_t * out, uint8_t dlc) static
Parse a compact hex string back into bytes.
Parameters
raw Hex string.
out Output bytes.
dlc Max bytes.
Returns
Number of bytes parsed.
Definition at line 118 of file message_view.c.
References count, and hex_value().
Referenced by gui_refresh_trace_display().
timespec_to_ns()
static gint64 timespec_to_ns (const struct timespec * ts) static
Convert a timespec to nanoseconds.
Parameters
ts Time.
Returns
Nanoseconds.
Definition at line 135 of file message_view.c.
Referenced by gui_add_message().
format_timestamp()
static void format_timestamp (char * buf, size_t sz, const struct timespec * ts) static
Render a timespec as HH:MM:SS.mmm.
Parameters
buf Out.
sz Size.
ts Time.
Definition at line 141 of file message_view.c.
Referenced by gui_add_message().
format_interval()
static void format_interval (char * buf, size_t sz, gint64 delta_ns) static
Render an inter-frame interval in milliseconds.
Parameters
buf Out.
sz Size.
delta_ns Delta.
Definition at line 158 of file message_view.c.
Referenced by gui_add_message().
format_frequency()
static void format_frequency (char * buf, size_t sz, gint64 delta_ns) static
Render a frame frequency in hertz from an interval.
Parameters
buf Out.
sz Size.
delta_ns Delta.
Definition at line 170 of file message_view.c.
Referenced by gui_add_message().
should_rollup_message()
static gboolean should_rollup_message (const can_msg_t * msg) static
Decide whether msg should roll up onto an existing row.
Parameters
msg Frame.
Returns
TRUE to roll up.
< Frame direction: received.
Definition at line 189 of file message_view.c.
References CAN_DIR_RX, app_state_t::dedup_mode, can_msg_t::direction, g_app, and can_msg_t::is_error.
Referenced by gui_add_message().
gui_msg_type_str()
const char * gui_msg_type_str (const can_msg_t * m)
Return a short frame-type label ("Std", "Ext", "FD+BRS", …).
Parameters
m Frame.
Returns
Static string.
Definition at line 197 of file message_view.c.
References can_msg_t::is_brs, can_msg_t::is_error, can_msg_t::is_extended, can_msg_t::is_fd, and can_msg_t::is_remote.
Referenced by gui_add_message(), and trace_csv_write_row().
gui_bus_state_str()
const char * gui_bus_state_str (uint8_t st)
Return a bus-state label for a CAN_BUS_* value.
Parameters
st State.
Returns
Static string.
< Error-warning bus state.
< Error-passive bus state.
< Bus-off state.
Definition at line 205 of file message_view.c.
References CAN_BUS_OFF, CAN_BUS_PASSIVE, and CAN_BUS_WARNING.
Referenced by gui_update_stats().
gui_bus_state_color()
const char * gui_bus_state_color (uint8_t st)
Return a Pango colour name for a CAN_BUS_* value.
Parameters
st State.
Returns
Static string.
< Error-warning bus state.
< Error-passive bus state.
< Bus-off state.
Definition at line 215 of file message_view.c.
References CAN_BUS_OFF, CAN_BUS_PASSIVE, and CAN_BUS_WARNING.
Referenced by gui_update_stats().
row_fg()
static const char * row_fg (const can_msg_t * m) static
Return the row foreground colour for a frame, or NULL for default.
Parameters
m Frame.
Returns
Colour or NULL.
< Frame direction: transmitted.
Definition at line 227 of file message_view.c.
References CAN_DIR_TX, can_msg_t::direction, and can_msg_t::is_error.
Referenced by gui_add_message().
create_trace_view()
GtkWidget * create_trace_view (void)
Create the trace GtkTreeView and its backing GtkListStore.
Trace view factory implemented in message_view.c.
Returns
A scrolled-window container holding the tree view.
Definition at line 242 of file message_view.c.
References g_gui, TCOL_COUNT, TCOL_DATA, TCOL_DIR, TCOL_DLC, TCOL_FG, TCOL_FREQ, TCOL_ID, TCOL_ID_RAW, TCOL_INTERVAL, TCOL_NUM, TCOL_SEQ, TCOL_TIME, TCOL_TYPE, gui_widgets_t::trace_store, and gui_widgets_t::trace_view.
Referenced by gui_create_main_window().
create_stats_panel()
GtkWidget * create_stats_panel (void)
Create a vertical statistics panel (legacy/optional layout).
Returns
A framed grid of statistic labels.
Definition at line 318 of file message_view.c.
References ADD_ROW, g_gui, gui_widgets_t::lbl_bitrate, gui_widgets_t::lbl_bus_state, gui_widgets_t::lbl_connection, gui_widgets_t::lbl_err, gui_widgets_t::lbl_rx, gui_widgets_t::lbl_tx, and gui_widgets_t::progress_bus_load.
gui_add_message()
void gui_add_message (const can_msg_t * msg)
Append (or roll up) one frame into the trace view.
Parameters
msg Frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Frame direction: transmitted.
Definition at line 383 of file message_view.c.
References CAN_DIR_TX, can_msg_t::data, DATA_TEXT_MAX, can_msg_t::direction, can_msg_t::dlc, format_frequency(), format_interval(), format_raw_data(), format_timestamp(), FREQ_TEXT_MAX, g_gui, gui_format_data(), gui_format_id(), gui_msg_type_str(), can_msg_t::id, ID_TEXT_MAX, INTERVAL_TEXT_MAX, can_msg_t::is_extended, MAX_TRACE_ROWS, RAW_DATA_MAX, row_fg(), can_msg_t::seq, should_rollup_message(), TCOL_COUNT, TCOL_DATA, TCOL_DATA_RAW, TCOL_DIR, TCOL_DIR_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_FG, TCOL_FREQ, TCOL_ID, TCOL_ID_RAW, TCOL_INTERVAL, TCOL_SEQ, TCOL_TIME, TCOL_TS_NS, TCOL_TYPE, TIME_TEXT_MAX, timespec_to_ns(), can_msg_t::timestamp, gui_widgets_t::trace_store, and gui_widgets_t::trace_view.
Referenced by idle_add_message().
gui_clear_trace()
void gui_clear_trace (void)
Remove every row from the trace view.
Definition at line 513 of file message_view.c.
References g_gui, and gui_widgets_t::trace_store.
Referenced by on_clear(), and on_dedup_toggle().
gui_refresh_trace_display()
void gui_refresh_trace_display (void)
Re-render existing trace rows after a display-format change.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
Definition at line 519 of file message_view.c.
References CANFD_DATA_MAX, DATA_TEXT_MAX, g_gui, gui_format_data(), gui_format_id(), ID_TEXT_MAX, parse_raw_data(), TCOL_DATA, TCOL_DATA_RAW, TCOL_DLC, TCOL_EXT_RAW, TCOL_ID, TCOL_ID_RAW, and gui_widgets_t::trace_store.
Referenced by on_data_format_toggle(), and on_id_format_toggle().
gui_update_stats()
void gui_update_stats (void)
Refresh the statistics bar from g_app counters.
Definition at line 565 of file message_view.c.
References app_state_t::bitrate, app_state_t::bus_load, app_state_t::bus_state, app_state_t::connected, app_state_t::error_count, g_app, g_gui, gui_bus_state_color(), gui_bus_state_str(), app_state_t::iface, gui_widgets_t::lbl_bitrate, gui_widgets_t::lbl_bus_load, gui_widgets_t::lbl_bus_state, gui_widgets_t::lbl_connection, gui_widgets_t::lbl_err, gui_widgets_t::lbl_rx, gui_widgets_t::lbl_stats_summary, gui_widgets_t::lbl_tx, gui_widgets_t::progress_bus_load, app_state_t::rx_count, and app_state_t::tx_count.
Referenced by app_do_disconnect(), gui_create_main_window(), and idle_update_stats().
gui_status_message()
void gui_status_message (const char * fmt, ...)
Set the status-bar text (printf-style).
Parameters
fmt printf format string.
... Format arguments.
Definition at line 635 of file message_view.c.
References g_gui, gui_widgets_t::statusbar, and gui_widgets_t::statusbar_ctx.
Referenced by app_do_connect(), app_do_disconnect(), on_clear(), on_data_format_toggle(), on_dedup_toggle(), on_id_format_toggle(), on_trace_save(), on_trace_start(), and on_trace_stop().
gui_show_error()
void gui_show_error (GtkWidget * parent, const char * title, const char * msg)
Show a modal error dialog.
Parameters
parent Transient parent (may be NULL).
title Window title.
msg Message body.
Definition at line 653 of file message_view.c.
Referenced by app_do_connect(), on_trace_save(), and on_trace_start().