PCAN-View Linux: gui/settings_dialog.c File Reference
settings_dialog.c File Reference
Modal CAN connection-settings dialog.
#include <stdio.h>
#include <string.h>
#include <dirent.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/app_state.h"
#include "../inc/socketcan.h"
Macros
#define MAX_IF 32
#define GRID_LABEL(str)
Functions
static void populate_interfaces (GtkComboBoxText *combo)
Fill the interface combo with discovered CAN interfaces.
static void on_fd_toggled (GtkToggleButton *btn, gpointer data)
"Enable CAN FD" toggle handler — enables the data-rate widget.
void gui_show_settings_dialog (GtkWidget *parent)
Show the connection-settings dialog.
Variables
struct {
const char * label
uint32_t value
} s_bitrates []
struct {
const char * label
uint32_t value
} s_fd_bitrates []
Detailed Description
Modal CAN connection-settings dialog.
Presents the connection options and, on confirmation, writes them into g_app and triggers app_do_connect. The user can choose:
the CAN interface (auto-discovered from /sys/class/net, with vcan0 always offered as a fallback),
the nominal bit rate,
CAN FD mode and its data bit rate,
listen-only mode.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file settings_dialog.c.
Macro Definition Documentation
MAX_IF
#define MAX_IF 32
GRID_LABEL
#define GRID_LABEL (str)
Value:
    do { \
    GtkWidget *_l = gtk_label_new(str); \
    gtk_label_set_xalign(GTK_LABEL(_l), 1.0f); \
    gtk_grid_attach(GTK_GRID(grid), _l, 0, row, 1, 1); \
} while(0)
Function Documentation
populate_interfaces()
static void populate_interfaces (GtkComboBoxText * combo) static
Fill the interface combo with discovered CAN interfaces.
Always lists vcan0 first, then any other CAN interfaces, and pre-selects the one currently stored in g_app.
Parameters
combo The combo box to populate.
< Max interface-name buffer size (incl. NUL).
Definition at line 40 of file settings_dialog.c.
References g_app, app_state_t::iface, MAX_IF, socketcan_list_interfaces(), and SOCKETCAN_MAX_IFACE.
Referenced by gui_show_settings_dialog().
on_fd_toggled()
static void on_fd_toggled (GtkToggleButton * btn, gpointer data) static
"Enable CAN FD" toggle handler — enables the data-rate widget.
Parameters
btn The CAN FD check button.
data The data-bitrate widget to (de)sensitise.
Definition at line 110 of file settings_dialog.c.
Referenced by gui_show_settings_dialog().
gui_show_settings_dialog()
void gui_show_settings_dialog (GtkWidget * parent)
Show the connection-settings dialog.
Parameters
parent Transient parent.
< Max interface-name length in app state.
Definition at line 117 of file settings_dialog.c.
References app_do_connect(), app_do_disconnect(), APP_MAX_IFACE_LEN, app_state_t::bitrate, app_state_t::connected, app_state_t::data_bitrate, app_state_t::fd_mode, g_app, GRID_LABEL, app_state_t::iface, label, app_state_t::listen_only, on_fd_toggled(), populate_interfaces(), s_bitrates, s_fd_bitrates, and value.
Referenced by on_connect(), and on_settings().
Variable Documentation
label
const char* label
Definition at line 78 of file settings_dialog.c.
Referenced by gui_show_settings_dialog(), menu_item(), and txp_header_label().
value
uint32_t value
Definition at line 79 of file settings_dialog.c.
Referenced by dbc_extract_raw(), gui_plot_add_sample(), gui_show_settings_dialog(), and txp_build_frame().
[struct]
struct { ... } s_bitrates[]
Initial value:
= {
    { "10 kbit/s",   10000   },
    { "20 kbit/s",   20000   },
    { "50 kbit/s",   50000   },
    { "100 kbit/s", 100000   },
    { "125 kbit/s", 125000   },
    { "250 kbit/s", 250000   },
    { "500 kbit/s", 500000   },
    { "800 kbit/s", 800000   },
    { "1 Mbit/s",  1000000   },
}
Referenced by gui_show_settings_dialog().
[struct]
struct { ... } s_fd_bitrates[]
Initial value:
= {
    { "1 Mbit/s",   1000000  },
    { "2 Mbit/s",   2000000  },
    { "4 Mbit/s",   4000000  },
    { "5 Mbit/s",   5000000  },
    { "8 Mbit/s",   8000000  },
    { "10 Mbit/s", 10000000  },
    { "12 Mbit/s", 12000000  },
}
Referenced by gui_show_settings_dialog().