PCAN-View Linux: gui/signal_view.c File Reference
signal_view.c File Reference
Signal Analysis tab — live DBC-decoded individual-signal table.
#include <stdio.h>
#include <string.h>
#include <unistd.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/app_state.h"
#include "../inc/can_message.h"
#include "../inc/dbc.h"
Enumerations
enum {
SCOL_MSG = 0 , SCOL_ID , SCOL_SIGNAL , SCOL_RAW ,
SCOL_VALUE , SCOL_UNIT , SCOL_RANGE , SCOL_COUNT ,
SCOL_FG , SCOL_MSGID , SCOL_EXT , SCOL_SIGIDX ,
SCOL_NUM
}
Column indices of the Signal Analysis GtkListStore.
Functions
const char * gui_find_asset (const char *name)
Resolve a bundled asset path (defined in main_window.c).
static void fmt_double (char *buf, size_t sz, double v)
Format a physical/raw double compactly (trim trailing zeros).
static void sig_table_rebuild (void)
Rebuild the signal table from the active database (s_db).
static void sig_update_dbc_label (void)
Refresh the "loaded database" status label.
gboolean gui_signal_load_dbc (const char *path)
Load (or replace) the active CAN database for signal decoding.
void gui_signal_clear_dbc (void)
Forget the active database and clear the signal table.
void gui_signal_load_default_dbc (void)
Auto-load the bundled demo database if one is found.
void gui_signal_decode_message (const can_msg_t *msg)
Decode one frame against the active database and update the signal rows.
static void on_load_dbc (GtkWidget *w, gpointer d)
"Load DBC…" — choose and load a database file.
static void on_reload_dbc (GtkWidget *w, gpointer d)
"Reload" — re-read the active database from disk.
static void on_clear_dbc (GtkWidget *w, gpointer d)
"Clear" — unload the active database.
GtkWidget * gui_create_signal_view (void)
Build the Signal Analysis tab (live DBC-decoded signal table).
Variables
static dbc_db_t * s_db = NULL
The active CAN database, or NULL when none is loaded.
Detailed Description
Signal Analysis tab — live DBC-decoded individual-signal table.
Implements a Vector-CANalyzer-style signal view: a CAN database (DBC) is loaded, every signal it defines becomes a row, and as frames arrive each matching signal's raw and physical values update live. The decoding itself lives in the GTK-independent driver/dbc.c; this file owns the active database (s_db), builds the GtkTreeView, and bridges incoming can_msg_t frames to row updates on the GTK main thread.
Layout of one Signal Analysis page:
*   GtkBox (vertical)
*   ├─ toolbar  (Load DBC… / Reload / Clear  +  loaded-file label)
*   └─ scrolled GtkTreeView   (Message | ID | Signal | Raw | Value | Unit | …)
*
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file signal_view.c.
Enumeration Type Documentation
anonymous enum
anonymous enum
Column indices of the Signal Analysis GtkListStore.
Enumerator
SCOL_MSG
Message name.
SCOL_ID
Formatted CAN identifier.
SCOL_SIGNAL
Signal name.
SCOL_RAW
Raw (unscaled) value.
SCOL_VALUE
Physical value.
SCOL_UNIT
Engineering unit.
SCOL_RANGE
Documented min..max.
SCOL_COUNT
Update hit count.
SCOL_FG
Row foreground (NULL until first update).
SCOL_MSGID
Hidden: raw CAN id for matching.
SCOL_EXT
Hidden: extended-ID flag for matching.
SCOL_SIGIDX
Hidden: signal index within its message.
SCOL_NUM
Model width.
Definition at line 45 of file signal_view.c.
Function Documentation
gui_find_asset()
const char * gui_find_asset (const char * name) extern
Resolve a bundled asset path (defined in main_window.c).
Resolve a bundled asset path (defined in main_window.c).
Searches, in order: $PCAN_VIEW_ASSET_DIR, paths relative to the executable (dev assets/ and installed ../share/pcan-view), and the system share dirs.
Parameters
name Asset filename (e.g. "taksys_logo.png").
Returns
Static path string valid until the next call, or NULL if not found.
Definition at line 66 of file main_window.c.
Referenced by gui_load_logo(), and gui_signal_load_default_dbc().
fmt_double()
static void fmt_double (char * buf, size_t sz, double v) static
Format a physical/raw double compactly (trim trailing zeros).
Parameters
buf Output.
sz Size.
v Value.
Definition at line 65 of file signal_view.c.
Referenced by gui_signal_decode_message(), and sig_table_rebuild().
sig_table_rebuild()
static void sig_table_rebuild (void) static
Rebuild the signal table from the active database (s_db).
Definition at line 86 of file signal_view.c.
References fmt_double(), g_gui, gui_format_id(), dbc_message_t::id, dbc_message_t::is_extended, dbc_signal_t::max, dbc_db_t::message_count, dbc_db_t::messages, dbc_signal_t::min, dbc_signal_t::name, dbc_message_t::name, s_db, SCOL_COUNT, SCOL_EXT, SCOL_FG, SCOL_ID, SCOL_MSG, SCOL_MSGID, SCOL_RANGE, SCOL_RAW, SCOL_SIGIDX, SCOL_SIGNAL, SCOL_UNIT, SCOL_VALUE, gui_widgets_t::sig_store, dbc_message_t::signal_count, dbc_message_t::signals, and dbc_signal_t::unit.
Referenced by gui_signal_clear_dbc(), and gui_signal_load_dbc().
sig_update_dbc_label()
static void sig_update_dbc_label (void) static
Refresh the "loaded database" status label.
Definition at line 134 of file signal_view.c.
References g_gui, gui_widgets_t::lbl_dbc, dbc_db_t::message_count, dbc_db_t::path, s_db, and dbc_db_t::signal_count.
Referenced by gui_create_signal_view(), gui_signal_clear_dbc(), gui_signal_load_dbc(), and gui_signal_load_default_dbc().
gui_signal_load_dbc()
gboolean gui_signal_load_dbc (const char * path)
Load (or replace) the active CAN database for signal decoding.
Parameters
path Path to a .dbc file.
Returns
TRUE on success; on failure a status message is shown and the previous database (if any) is kept.
Definition at line 152 of file signal_view.c.
References dbc_free(), dbc_load_file(), gui_plot_set_database(), gui_status_message(), dbc_db_t::message_count, dbc_db_t::path, s_db, sig_table_rebuild(), sig_update_dbc_label(), and dbc_db_t::signal_count.
Referenced by gui_signal_load_default_dbc(), on_db_load(), on_load_dbc(), and on_reload_dbc().
gui_signal_clear_dbc()
void gui_signal_clear_dbc (void)
Forget the active database and clear the signal table.
Definition at line 176 of file signal_view.c.
References dbc_free(), gui_plot_set_database(), gui_status_message(), s_db, sig_table_rebuild(), and sig_update_dbc_label().
Referenced by on_clear_dbc(), and on_db_clear().
gui_signal_load_default_dbc()
void gui_signal_load_default_dbc (void)
Auto-load the bundled demo database if one is found.
Definition at line 188 of file signal_view.c.
References gui_find_asset(), gui_signal_load_dbc(), and sig_update_dbc_label().
Referenced by gui_create_main_window(), on_db_demo(), and on_reload_dbc().
gui_signal_decode_message()
void gui_signal_decode_message (const can_msg_t * msg)
Decode one frame against the active database and update the signal rows.
Parameters
msg Frame (RX or TX); ignored when no database is loaded.
< Frame direction: transmitted.
Definition at line 201 of file signal_view.c.
References CAN_DIR_TX, can_msg_t::data, dbc_decode_physical(), dbc_extract_raw(), dbc_find_message(), can_msg_t::direction, can_msg_t::dlc, fmt_double(), g_gui, gui_plot_add_sample(), can_msg_t::id, dbc_message_t::id, can_msg_t::is_error, can_msg_t::is_extended, dbc_message_t::is_extended, s_db, SCOL_COUNT, SCOL_EXT, SCOL_FG, SCOL_MSGID, SCOL_RAW, SCOL_SIGIDX, SCOL_VALUE, gui_widgets_t::sig_store, dbc_message_t::signal_count, and dbc_message_t::signals.
Referenced by gui_add_message().
on_load_dbc()
static void on_load_dbc (GtkWidget * w, gpointer d) static
"Load DBC…" — choose and load a database file.
Definition at line 257 of file signal_view.c.
References g_gui, gui_signal_load_dbc(), and gui_widgets_t::window.
Referenced by gui_create_signal_view().
on_reload_dbc()
static void on_reload_dbc (GtkWidget * w, gpointer d) static
"Reload" — re-read the active database from disk.
Definition at line 286 of file signal_view.c.
References gui_signal_load_dbc(), gui_signal_load_default_dbc(), dbc_db_t::path, and s_db.
Referenced by gui_create_signal_view().
on_clear_dbc()
static void on_clear_dbc (GtkWidget * w, gpointer d) static
"Clear" — unload the active database.
Definition at line 302 of file signal_view.c.
References gui_signal_clear_dbc().
Referenced by gui_create_signal_view().
gui_create_signal_view()
GtkWidget * gui_create_signal_view (void)
Build the Signal Analysis tab (live DBC-decoded signal table).
Returns
A container widget for use as a notebook page.
Definition at line 312 of file signal_view.c.
References g_gui, gui_widgets_t::lbl_dbc, on_clear_dbc(), on_load_dbc(), on_reload_dbc(), SCOL_COUNT, SCOL_FG, SCOL_ID, SCOL_MSG, SCOL_NUM, SCOL_RANGE, SCOL_RAW, SCOL_SIGNAL, SCOL_UNIT, SCOL_VALUE, gui_widgets_t::sig_store, sig_update_dbc_label(), and gui_widgets_t::sig_view.
Referenced by gui_create_main_window().
Variable Documentation
s_db
dbc_db_t* s_db = NULL static
The active CAN database, or NULL when none is loaded.
Definition at line 40 of file signal_view.c.
Referenced by gui_signal_clear_dbc(), gui_signal_decode_message(), gui_signal_load_dbc(), on_reload_dbc(), sig_table_rebuild(), and sig_update_dbc_label().