PCAN-View Linux: gui/signal_plot.c File Reference
signal_plot.c File Reference
Signal Analysis Viewer — multi-signal value-over-time graph (Cairo).
#include <math.h>
#include <stdio.h>
#include <string.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/dbc.h"
Data Structures
struct plot_series_t
One plottable signal with its rolling sample history.
Macros
#define PLOT_RING 30000
Samples kept per series (~30 s @ 1 kHz).
#define PLOT_REDRAW_MS 33
Redraw period (~30 fps) while mapped.
#define PALETTE_N ((int)(sizeof(PALETTE) / sizeof(PALETTE[0])))
Functions
static double plot_now (void)
Seconds elapsed since the plot's monotonic origin.
static void plot_free_series (void)
Free the current series array and clear the selector list.
static void on_series_toggled (GtkToggleButton *btn, gpointer data)
Selector check-button toggled — enable/disable a series.
void gui_plot_set_database (const dbc_db_t *db)
Rebuild the plot's series list from a database (or clear it).
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
static double norm_to_y (double norm, double y0, double y1)
Map a normalised value (0..1) to a Y pixel within the plot rect.
static gboolean on_draw (GtkWidget *w, cairo_t *cr, gpointer data)
Cairo draw handler for the graph.
static gboolean plot_tick (gpointer data)
Redraw timer — repaint while the page is visible and data changed.
static void on_select_all (GtkWidget *w, gpointer d)
"Select All" — enable every series.
static void on_select_none (GtkWidget *w, gpointer d)
"Clear Selection" — disable every series.
static void on_reset (GtkWidget *w, gpointer d)
"Reset" — drop all buffered samples and restart the time origin.
static void on_pause (GtkToggleButton *btn, gpointer d)
Pause toggle — freeze/resume sample intake.
static void on_window_changed (GtkSpinButton *btn, gpointer d)
Window-width spin — change the visible time span.
static void on_destroy (GtkWidget *w, gpointer d)
Free the redraw timer when the page is destroyed.
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
Variables
static const double PALETTE [][3]
Distinct trace colours (RGB 0..1), cycled across series.
struct {
plot_series_t * series
Dynamically sized series array.
int n_series
Number of series.
GtkWidget * area
The Cairo drawing area.
GtkWidget * list_box
Selector check-button container.
double window_sec
Visible time window width (seconds).
gint64 start_us
Monotonic origin for sample times.
gboolean paused
Freeze sample intake when TRUE.
gboolean dirty
New data since the last repaint.
guint timer_id
Redraw timer source id.
} s_plot
Detailed Description
Signal Analysis Viewer — multi-signal value-over-time graph (Cairo).
Implements a Vector-CANalyzer "Graphics"-style oscilloscope tab: any subset of the signals defined by the loaded DBC can be selected and plotted together on one time axis. Each decoded sample (delivered from the Signal Analysis decode path via gui_plot_add_sample) is appended to a per-signal ring buffer; a Cairo GtkDrawingArea renders a scrolling window of the most recent samples.
Because signals have wildly different physical ranges (rpm vs. °C vs. %), each trace is normalised to its DBC [min,max] range so all selected signals share the vertical space; the legend reports each signal's real latest value and unit. A redraw timer repaints at ~30 fps only while the page is mapped, and the visible-window width is adjustable.
All sample appends and draws happen on the GTK main thread (the decode path runs in a GLib idle callback), so no locking is required.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file signal_plot.c.
Macro Definition Documentation
PLOT_RING
#define PLOT_RING 30000
Samples kept per series (~30 s @ 1 kHz).
Definition at line 35 of file signal_plot.c.
PLOT_REDRAW_MS
#define PLOT_REDRAW_MS 33
Redraw period (~30 fps) while mapped.
Definition at line 36 of file signal_plot.c.
PALETTE_N
#define PALETTE_N ((int)(sizeof(PALETTE) / sizeof(PALETTE[0])))
Definition at line 45 of file signal_plot.c.
Function Documentation
plot_now()
static double plot_now (void) static
Seconds elapsed since the plot's monotonic origin.
Definition at line 83 of file signal_plot.c.
References s_plot.
Referenced by gui_plot_add_sample(), and on_draw().
plot_free_series()
static void plot_free_series (void) static
Free the current series array and clear the selector list.
Definition at line 95 of file signal_plot.c.
References s_plot.
Referenced by gui_plot_set_database().
on_series_toggled()
static void on_series_toggled (GtkToggleButton * btn, gpointer data) static
Selector check-button toggled — enable/disable a series.
Definition at line 111 of file signal_plot.c.
References s_plot.
Referenced by gui_plot_set_database().
gui_plot_set_database()
void gui_plot_set_database (const dbc_db_t * db)
Rebuild the plot's series list from a database (or clear it).
Parameters
db Active database, or NULL to remove all series.
< Max message/signal name length.
Definition at line 121 of file signal_plot.c.
References plot_series_t::check, plot_series_t::col, DBC_NAME_MAX, plot_series_t::dmax, plot_series_t::dmin, plot_series_t::enabled, plot_series_t::ext, plot_series_t::id, dbc_message_t::id, dbc_message_t::is_extended, plot_series_t::label, dbc_signal_t::max, dbc_db_t::message_count, dbc_db_t::messages, dbc_signal_t::min, dbc_signal_t::name, dbc_message_t::name, on_series_toggled(), PALETTE, PALETTE_N, plot_free_series(), s_plot, plot_series_t::sig_idx, dbc_message_t::signal_count, dbc_db_t::signal_count, dbc_message_t::signals, plot_series_t::unit, and dbc_signal_t::unit.
Referenced by gui_signal_clear_dbc(), and gui_signal_load_dbc().
gui_plot_add_sample()
void gui_plot_add_sample (uint32_t id, int is_ext, int sig_idx, double value)
Append a decoded sample to a plot series (timestamped "now").
Parameters
id Raw CAN identifier.
is_ext Non-zero for an extended-ID message.
sig_idx Signal index within its message.
value Physical value.
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
Definition at line 185 of file signal_plot.c.
References plot_series_t::count, plot_series_t::ext, plot_series_t::has_last, plot_series_t::head, plot_series_t::id, plot_series_t::last, plot_now(), PLOT_RING, s_plot, plot_series_t::sig_idx, plot_series_t::t, plot_series_t::v, and value.
Referenced by gui_signal_decode_message().
norm_to_y()
static double norm_to_y (double norm, double y0, double y1) static
Map a normalised value (0..1) to a Y pixel within the plot rect.
Definition at line 214 of file signal_plot.c.
Referenced by on_draw().
on_draw()
static gboolean on_draw (GtkWidget * w, cairo_t * cr, gpointer data) static
Cairo draw handler for the graph.
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
< Samples kept per series (~30 s @ 1 kHz).
< Max message/signal name length.
Definition at line 224 of file signal_plot.c.
References plot_series_t::col, plot_series_t::count, DBC_NAME_MAX, plot_series_t::dmax, plot_series_t::dmin, plot_series_t::enabled, plot_series_t::has_last, plot_series_t::head, plot_series_t::label, plot_series_t::last, norm_to_y(), plot_now(), PLOT_RING, s_plot, plot_series_t::t, plot_series_t::unit, and plot_series_t::v.
Referenced by gui_create_signal_plot().
plot_tick()
static gboolean plot_tick (gpointer data) static
Redraw timer — repaint while the page is visible and data changed.
Definition at line 378 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
on_select_all()
static void on_select_all (GtkWidget * w, gpointer d) static
"Select All" — enable every series.
Definition at line 395 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
on_select_none()
static void on_select_none (GtkWidget * w, gpointer d) static
"Clear Selection" — disable every series.
Definition at line 404 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
on_reset()
static void on_reset (GtkWidget * w, gpointer d) static
"Reset" — drop all buffered samples and restart the time origin.
Definition at line 413 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
on_pause()
static void on_pause (GtkToggleButton * btn, gpointer d) static
Pause toggle — freeze/resume sample intake.
Definition at line 426 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
on_window_changed()
static void on_window_changed (GtkSpinButton * btn, gpointer d) static
Window-width spin — change the visible time span.
Definition at line 433 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
on_destroy()
static void on_destroy (GtkWidget * w, gpointer d) static
Free the redraw timer when the page is destroyed.
Definition at line 440 of file signal_plot.c.
References s_plot.
Referenced by gui_create_signal_plot().
gui_create_signal_plot()
GtkWidget * gui_create_signal_plot (void)
Build the Signal Analysis Viewer tab (multi-signal time graph).
Returns
A container widget for use as a notebook page.
< Redraw period (~30 fps) while mapped.
Definition at line 453 of file signal_plot.c.
References on_destroy(), on_draw(), on_pause(), on_reset(), on_select_all(), on_select_none(), on_window_changed(), PLOT_REDRAW_MS, plot_tick(), and s_plot.
Referenced by gui_create_main_window().
Variable Documentation
PALETTE
const double PALETTE[][3] static
Initial value:
= {
    { 0.20, 0.60, 0.86 }, { 0.91, 0.30, 0.24 }, { 0.18, 0.80, 0.44 },
    { 0.95, 0.61, 0.07 }, { 0.61, 0.35, 0.71 }, { 0.10, 0.74, 0.61 },
    { 0.90, 0.49, 0.13 }, { 0.52, 0.58, 0.59 }, { 0.83, 0.33, 0.64 },
    { 0.16, 0.50, 0.73 }, { 0.86, 0.78, 0.13 }, { 0.40, 0.76, 0.65 },
}
Distinct trace colours (RGB 0..1), cycled across series.
Definition at line 39 of file signal_plot.c.
Referenced by gui_plot_set_database().
series
plot_series_t* series
Dynamically sized series array.
Definition at line 71 of file signal_plot.c.
n_series
int n_series
Number of series.
Definition at line 72 of file signal_plot.c.
area
GtkWidget* area
The Cairo drawing area.
Definition at line 73 of file signal_plot.c.
list_box
GtkWidget* list_box
Selector check-button container.
Definition at line 74 of file signal_plot.c.
window_sec
double window_sec
Visible time window width (seconds).
Definition at line 75 of file signal_plot.c.
start_us
gint64 start_us
Monotonic origin for sample times.
Definition at line 76 of file signal_plot.c.
paused
gboolean paused
Freeze sample intake when TRUE.
Definition at line 77 of file signal_plot.c.
dirty
gboolean dirty
New data since the last repaint.
Definition at line 78 of file signal_plot.c.
timer_id
guint timer_id
Redraw timer source id.
Definition at line 79 of file signal_plot.c.
[struct]
struct { ... } s_plot
Referenced by gui_create_signal_plot(), gui_plot_add_sample(), gui_plot_set_database(), on_destroy(), on_draw(), on_pause(), on_reset(), on_select_all(), on_select_none(), on_series_toggled(), on_window_changed(), plot_free_series(), plot_now(), and plot_tick().