PCAN-View Linux: inc/socketcan.h File Reference
socketcan.h File Reference
SocketCAN back-end interface (Linux PF_CAN / SOCK_RAW).
#include <stdint.h>
#include "can_message.h"
#include "drv_can.h"
Data Structures
struct socketcan_ctx_t
State for one open SocketCAN connection.
Macros
#define SOCKETCAN_MAX_IFACE 32
Max interface-name buffer size (incl.
Functions
int socketcan_open (socketcan_ctx_t *ctx, const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Open and configure a SocketCAN interface.
int socketcan_close (socketcan_ctx_t *ctx)
Close the socket (and bring real interfaces down).
int socketcan_send (socketcan_ctx_t *ctx, const can_msg_t *msg)
Write one frame to the bus.
int socketcan_recv (socketcan_ctx_t *ctx, can_msg_t *msg, int timeout_ms)
Read one frame with a timeout.
int socketcan_get_stats (socketcan_ctx_t *ctx, can_stats_t *stats)
Statistics hook (app-maintained; returns OK).
int socketcan_set_filter (socketcan_ctx_t *ctx, uint32_t id, uint32_t mask, int is_extended)
Install a CAN_RAW_FILTER acceptance filter.
int socketcan_clear_filter (socketcan_ctx_t *ctx)
Clear all acceptance filters.
int socketcan_reset (socketcan_ctx_t *ctx)
Bounce the interface down/up.
const char * socketcan_error_string (int err)
Map a DRV_CAN_* code to text.
int socketcan_list_interfaces (char ifnames[][32], int max_count)
Enumerate available CAN-type interfaces from /sys/class/net.
Detailed Description
SocketCAN back-end interface (Linux PF_CAN / SOCK_RAW).
Declares the per-connection context (socketcan_ctx_t) and the low-level SocketCAN operations that implement the generic can_driver_t vtable. Interface bring-up/configuration is performed via the ip utility (elevated through pkexec when required), avoiding a bespoke Netlink implementation.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file socketcan.h.
Macro Definition Documentation
SOCKETCAN_MAX_IFACE
#define SOCKETCAN_MAX_IFACE 32
Max interface-name buffer size (incl.
NUL).
Definition at line 22 of file socketcan.h.
Function Documentation
socketcan_open()
int socketcan_open (socketcan_ctx_t * ctx, const char * iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t * timing)
Open and configure a SocketCAN interface.
Parameters
ctx Context to initialise (zeroed on entry).
iface Interface name; vcan* interfaces are auto-created/up'd.
bitrate Nominal bit rate (bit/s).
data_bitrate CAN FD data bit rate (bit/s); 0 if unused.
fd_mode Non-zero to request CAN FD.
listen_only Non-zero for passive monitoring.
timing Optional manual bit timing (may be NULL).
Returns
DRV_CAN_OK or a negative DRV_CAN_ERR_* code.
< Invalid argument.
< Initialisation failed.
< Initialisation failed.
< Initialisation failed.
< Initialisation failed.
< Initialisation failed.
< Operation succeeded.
Definition at line 293 of file socketcan.c.
References socketcan_ctx_t::bitrate, configure_interface(), socketcan_ctx_t::data_bitrate, DRV_CAN_ERR_INIT, DRV_CAN_ERR_PARAM, DRV_CAN_OK, can_bit_timing_t::enabled, socketcan_ctx_t::fd_enabled, socketcan_ctx_t::iface, iface_is_up(), socketcan_ctx_t::listen_only, run_ip_priv(), socketcan_ctx_t::sock_fd, socketcan_iface_name_valid(), and socketcan_ctx_t::timing.
Referenced by sck_init().
socketcan_close()
int socketcan_close (socketcan_ctx_t * ctx)
Close the socket (and bring real interfaces down).
Parameters
ctx Context.
Returns
Status.
< Invalid argument.
< Operation succeeded.
Definition at line 399 of file socketcan.c.
References DRV_CAN_ERR_PARAM, DRV_CAN_OK, socketcan_ctx_t::iface, run_ip_priv(), and socketcan_ctx_t::sock_fd.
Referenced by sck_deinit().
socketcan_send()
int socketcan_send (socketcan_ctx_t * ctx, const can_msg_t * msg)
Write one frame to the bus.
Parameters
ctx Context.
msg Frame.
Returns
Status.
< Invalid argument.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Generic failure.
< Maximum payload of a classic CAN frame.
< Maximum payload of a classic CAN frame.
< Generic failure.
< Operation succeeded.
Definition at line 418 of file socketcan.c.
References CAN_MAX_DLC, CANFD_DATA_MAX, can_msg_t::data, can_msg_t::dlc, DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_OK, socketcan_ctx_t::fd_enabled, can_msg_t::id, can_msg_t::is_brs, can_msg_t::is_esi, can_msg_t::is_extended, can_msg_t::is_fd, can_msg_t::is_remote, and socketcan_ctx_t::sock_fd.
Referenced by sck_send().
socketcan_recv()
int socketcan_recv (socketcan_ctx_t * ctx, can_msg_t * msg, int timeout_ms)
Read one frame with a timeout.
Parameters
ctx Context.
msg Output frame.
timeout_ms Timeout in milliseconds (<0 blocks).
Returns
DRV_CAN_OK, DRV_CAN_ERR_TIMEOUT, or another code.
< Invalid argument.
< Generic failure.
< Operation timed out.
< Generic failure.
< Frame direction: received.
< Operation succeeded.
Definition at line 451 of file socketcan.c.
References CAN_DIR_RX, can_msg_t::data, can_msg_t::direction, can_msg_t::dlc, DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_ERR_TIMEOUT, DRV_CAN_OK, socketcan_ctx_t::fd_enabled, can_msg_t::id, can_msg_t::is_brs, can_msg_t::is_error, can_msg_t::is_esi, can_msg_t::is_extended, can_msg_t::is_fd, can_msg_t::is_remote, socketcan_ctx_t::sock_fd, and can_msg_t::timestamp.
Referenced by sck_recv().
socketcan_get_stats()
int socketcan_get_stats (socketcan_ctx_t * ctx, can_stats_t * stats)
Statistics hook (app-maintained; returns OK).
Parameters
ctx Context.
stats Output.
Returns
Status.
< Operation succeeded.
Definition at line 506 of file socketcan.c.
References DRV_CAN_OK.
Referenced by sck_get_stats().
socketcan_set_filter()
int socketcan_set_filter (socketcan_ctx_t * ctx, uint32_t id, uint32_t mask, int is_extended)
Install a CAN_RAW_FILTER acceptance filter.
Parameters
ctx Context.
id Filter id.
mask Filter mask.
is_extended Non-zero for extended IDs.
Returns
Status.
< Invalid argument.
< Generic failure.
< Operation succeeded.
Definition at line 514 of file socketcan.c.
References DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_OK, and socketcan_ctx_t::sock_fd.
Referenced by sck_set_filter().
socketcan_clear_filter()
int socketcan_clear_filter (socketcan_ctx_t * ctx)
Clear all acceptance filters.
Parameters
ctx Context.
Returns
Status.
< Invalid argument.
< Generic failure.
< Operation succeeded.
Definition at line 532 of file socketcan.c.
References DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_OK, and socketcan_ctx_t::sock_fd.
Referenced by sck_clear_filter().
socketcan_reset()
int socketcan_reset (socketcan_ctx_t * ctx)
Bounce the interface down/up.
Parameters
ctx Context.
Returns
Status.
< Invalid argument.
< Operation succeeded.
Definition at line 546 of file socketcan.c.
References DRV_CAN_ERR_PARAM, DRV_CAN_OK, socketcan_ctx_t::iface, and run_ip_priv().
Referenced by sck_reset().
socketcan_error_string()
const char * socketcan_error_string (int err)
Map a DRV_CAN_* code to text.
Parameters
err Code.
Returns
Static string.
< Operation succeeded.
< Generic failure.
< Operation timed out.
< Invalid argument.
< Initialisation failed.
Definition at line 562 of file socketcan.c.
References DRV_CAN_ERR, DRV_CAN_ERR_INIT, DRV_CAN_ERR_PARAM, DRV_CAN_ERR_TIMEOUT, and DRV_CAN_OK.
Referenced by drv_can_error_string(), and sck_error_string().
socketcan_list_interfaces()
int socketcan_list_interfaces (char ifnames[][32], int max_count)
Enumerate available CAN-type interfaces from /sys/class/net.
Parameters
ifnames Output array of name buffers.
max_count Capacity of ifnames.
Returns
Number of interfaces written.
< Max interface-name buffer size (incl. NUL).
Definition at line 574 of file socketcan.c.
References count, and SOCKETCAN_MAX_IFACE.
Referenced by populate_interfaces().