PCAN-View Linux: driver/socketcan.c File Reference
socketcan.c File Reference
SocketCAN back-end for PCAN-View Linux (PF_CAN / SOCK_RAW).
#include <stdio.h>
#include <stdlib.h>
#include <stdarg.h>
#include <string.h>
#include <errno.h>
#include <ctype.h>
#include <unistd.h>
#include <dirent.h>
#include <fcntl.h>
#include <sys/types.h>
#include <sys/socket.h>
#include <sys/ioctl.h>
#include <sys/select.h>
#include <sys/wait.h>
#include <net/if.h>
#include <linux/can.h>
#include <linux/can/raw.h>
#include <linux/can/error.h>
#include "../inc/socketcan.h"
#include "../inc/drv_can.h"
#include "../inc/can_message.h"
Functions
static int socketcan_iface_name_valid (const char *iface)
static int iface_is_up (const char *iface)
Return non-zero if interface iface currently has IFF_UP.
static const char * ip_tool_path (void)
Locate an absolute path to the ip tool (pkexec ignores $PATH).
static int run_argv (const char *const argv[], int quiet_stderr)
Fork/exec argv and wait for completion.
static int run_ip_priv (const char *const ip_argv[], int quiet_stderr)
Run an ip … command, retrying through pkexec if it fails.
static int configure_interface (const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Bring an interface down, apply CAN/CAN FD timing, and bring it up.
int socketcan_open (socketcan_ctx_t *ctx, const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Open and configure a SocketCAN interface.
int socketcan_close (socketcan_ctx_t *ctx)
Close the socket (and bring real interfaces down).
int socketcan_send (socketcan_ctx_t *ctx, const can_msg_t *msg)
Write one frame to the bus.
int socketcan_recv (socketcan_ctx_t *ctx, can_msg_t *msg, int timeout_ms)
Read one frame with a timeout.
int socketcan_get_stats (socketcan_ctx_t *ctx, can_stats_t *stats)
Statistics hook (app-maintained; returns OK).
int socketcan_set_filter (socketcan_ctx_t *ctx, uint32_t id, uint32_t mask, int is_extended)
Install a CAN_RAW_FILTER acceptance filter.
int socketcan_clear_filter (socketcan_ctx_t *ctx)
Clear all acceptance filters.
int socketcan_reset (socketcan_ctx_t *ctx)
Bounce the interface down/up.
const char * socketcan_error_string (int err)
Map a DRV_CAN_* code to text.
int socketcan_list_interfaces (char ifnames[][32], int max_count)
Enumerate available CAN-type interfaces from /sys/class/net.
Detailed Description
SocketCAN back-end for PCAN-View Linux (PF_CAN / SOCK_RAW).
Implements the socketcan_* operations declared in socketcan.h on top of the Linux SocketCAN subsystem. Interface bring-up and bit-rate configuration are delegated to the ip utility (run directly when the process already has CAP_NET_ADMIN, otherwise transparently re-tried through pkexec for a graphical authentication) so no bespoke Netlink code is required. Classic CAN and CAN FD frames are both supported.
See also
https://www.kernel.org/doc/Documentation/networking/can.rst
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file socketcan.c.
Function Documentation
socketcan_iface_name_valid()
static int socketcan_iface_name_valid (const char * iface) static
< Max interface-name buffer size (incl. NUL).
Definition at line 49 of file socketcan.c.
References SOCKETCAN_MAX_IFACE.
Referenced by socketcan_open().
iface_is_up()
static int iface_is_up (const char * iface) static
Return non-zero if interface iface currently has IFF_UP.
Definition at line 67 of file socketcan.c.
Referenced by socketcan_open().
ip_tool_path()
static const char * ip_tool_path (void) static
Locate an absolute path to the ip tool (pkexec ignores $PATH).
Definition at line 81 of file socketcan.c.
Referenced by run_ip_priv().
run_argv()
static int run_argv (const char *const argv[], int quiet_stderr) static
Fork/exec argv and wait for completion.
Parameters
argv NULL-terminated argument vector (argv[0] is the program).
quiet_stderr Non-zero to redirect the child's stderr to /dev/null.
Returns
0 if the child exited with status 0, -1 otherwise.
Definition at line 98 of file socketcan.c.
Referenced by run_ip_priv().
run_ip_priv()
static int run_ip_priv (const char *const ip_argv[], int quiet_stderr) static
Run an ip … command, retrying through pkexec if it fails.
Tries the command directly first (succeeds with CAP_NET_ADMIN); on failure it re-runs pkexec <abs ip> <args…> for a graphical polkit prompt, so the user can bring up vcan/CAN interfaces without a terminal sudo.
Parameters
ip_argv ip argument vector (argv[0] == "ip").
quiet_stderr Non-zero to silence stderr on the elevated attempt.
Returns
0 on success, -1 otherwise.
Definition at line 138 of file socketcan.c.
References ip_tool_path(), and run_argv().
Referenced by configure_interface(), socketcan_close(), socketcan_open(), and socketcan_reset().
configure_interface()
static int configure_interface (const char * iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t * timing) static
Bring an interface down, apply CAN/CAN FD timing, and bring it up.
Parameters
iface Interface name.
bitrate Nominal bit rate (bit/s).
data_bitrate CAN FD data bit rate (bit/s).
fd_mode Non-zero to enable CAN FD.
listen_only Non-zero for listen-only mode.
timing Optional manual bit timing (may be NULL).
Returns
0 on success, -1 on failure.
Definition at line 167 of file socketcan.c.
References can_bit_timing_t::brp, can_bit_timing_t::enabled, can_bit_timing_t::phase_seg1, can_bit_timing_t::phase_seg2, can_bit_timing_t::prop_seg, run_ip_priv(), can_bit_timing_t::sample_point, and can_bit_timing_t::sjw.
Referenced by socketcan_open().
socketcan_open()
int socketcan_open (socketcan_ctx_t * ctx, const char * iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t * timing)
Open and configure a SocketCAN interface.
Parameters
ctx Context to initialise (zeroed on entry).
iface Interface name; vcan* interfaces are auto-created/up'd.
bitrate Nominal bit rate (bit/s).
data_bitrate CAN FD data bit rate (bit/s); 0 if unused.
fd_mode Non-zero to request CAN FD.
listen_only Non-zero for passive monitoring.
timing Optional manual bit timing (may be NULL).
Returns
DRV_CAN_OK or a negative DRV_CAN_ERR_* code.
< Invalid argument.
< Initialisation failed.
< Initialisation failed.
< Initialisation failed.
< Initialisation failed.
< Initialisation failed.
< Operation succeeded.
Definition at line 293 of file socketcan.c.
References socketcan_ctx_t::bitrate, configure_interface(), socketcan_ctx_t::data_bitrate, DRV_CAN_ERR_INIT, DRV_CAN_ERR_PARAM, DRV_CAN_OK, can_bit_timing_t::enabled, socketcan_ctx_t::fd_enabled, socketcan_ctx_t::iface, iface_is_up(), socketcan_ctx_t::listen_only, run_ip_priv(), socketcan_ctx_t::sock_fd, socketcan_iface_name_valid(), and socketcan_ctx_t::timing.
Referenced by sck_init().
socketcan_close()
int socketcan_close (socketcan_ctx_t * ctx)
Close the socket (and bring real interfaces down).
Parameters
ctx Context.
Returns
Status.
< Invalid argument.
< Operation succeeded.
Definition at line 399 of file socketcan.c.
References DRV_CAN_ERR_PARAM, DRV_CAN_OK, socketcan_ctx_t::iface, run_ip_priv(), and socketcan_ctx_t::sock_fd.
Referenced by sck_deinit().
socketcan_send()
int socketcan_send (socketcan_ctx_t * ctx, const can_msg_t * msg)
Write one frame to the bus.
Parameters
ctx Context.
msg Frame.
Returns
Status.
< Invalid argument.
< Maximum payload of a CAN FD frame.
< Maximum payload of a CAN FD frame.
< Generic failure.
< Maximum payload of a classic CAN frame.
< Maximum payload of a classic CAN frame.
< Generic failure.
< Operation succeeded.
Definition at line 418 of file socketcan.c.
References CAN_MAX_DLC, CANFD_DATA_MAX, can_msg_t::data, can_msg_t::dlc, DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_OK, socketcan_ctx_t::fd_enabled, can_msg_t::id, can_msg_t::is_brs, can_msg_t::is_esi, can_msg_t::is_extended, can_msg_t::is_fd, can_msg_t::is_remote, and socketcan_ctx_t::sock_fd.
Referenced by sck_send().
socketcan_recv()
int socketcan_recv (socketcan_ctx_t * ctx, can_msg_t * msg, int timeout_ms)
Read one frame with a timeout.
Parameters
ctx Context.
msg Output frame.
timeout_ms Timeout in milliseconds (<0 blocks).
Returns
DRV_CAN_OK, DRV_CAN_ERR_TIMEOUT, or another code.
< Invalid argument.
< Generic failure.
< Operation timed out.
< Generic failure.
< Frame direction: received.
< Operation succeeded.
Definition at line 451 of file socketcan.c.
References CAN_DIR_RX, can_msg_t::data, can_msg_t::direction, can_msg_t::dlc, DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_ERR_TIMEOUT, DRV_CAN_OK, socketcan_ctx_t::fd_enabled, can_msg_t::id, can_msg_t::is_brs, can_msg_t::is_error, can_msg_t::is_esi, can_msg_t::is_extended, can_msg_t::is_fd, can_msg_t::is_remote, socketcan_ctx_t::sock_fd, and can_msg_t::timestamp.
Referenced by sck_recv().
socketcan_get_stats()
int socketcan_get_stats (socketcan_ctx_t * ctx, can_stats_t * stats)
Statistics hook (app-maintained; returns OK).
Parameters
ctx Context.
stats Output.
Returns
Status.
< Operation succeeded.
Definition at line 506 of file socketcan.c.
References DRV_CAN_OK.
Referenced by sck_get_stats().
socketcan_set_filter()
int socketcan_set_filter (socketcan_ctx_t * ctx, uint32_t id, uint32_t mask, int is_extended)
Install a CAN_RAW_FILTER acceptance filter.
Parameters
ctx Context.
id Filter id.
mask Filter mask.
is_extended Non-zero for extended IDs.
Returns
Status.
< Invalid argument.
< Generic failure.
< Operation succeeded.
Definition at line 514 of file socketcan.c.
References DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_OK, and socketcan_ctx_t::sock_fd.
Referenced by sck_set_filter().
socketcan_clear_filter()
int socketcan_clear_filter (socketcan_ctx_t * ctx)
Clear all acceptance filters.
Parameters
ctx Context.
Returns
Status.
< Invalid argument.
< Generic failure.
< Operation succeeded.
Definition at line 532 of file socketcan.c.
References DRV_CAN_ERR, DRV_CAN_ERR_PARAM, DRV_CAN_OK, and socketcan_ctx_t::sock_fd.
Referenced by sck_clear_filter().
socketcan_reset()
int socketcan_reset (socketcan_ctx_t * ctx)
Bounce the interface down/up.
Parameters
ctx Context.
Returns
Status.
< Invalid argument.
< Operation succeeded.
Definition at line 546 of file socketcan.c.
References DRV_CAN_ERR_PARAM, DRV_CAN_OK, socketcan_ctx_t::iface, and run_ip_priv().
Referenced by sck_reset().
socketcan_error_string()
const char * socketcan_error_string (int err)
Map a DRV_CAN_* code to text.
Parameters
err Code.
Returns
Static string.
< Operation succeeded.
< Generic failure.
< Operation timed out.
< Invalid argument.
< Initialisation failed.
Definition at line 562 of file socketcan.c.
References DRV_CAN_ERR, DRV_CAN_ERR_INIT, DRV_CAN_ERR_PARAM, DRV_CAN_ERR_TIMEOUT, and DRV_CAN_OK.
Referenced by drv_can_error_string(), and sck_error_string().
socketcan_list_interfaces()
int socketcan_list_interfaces (char ifnames[][32], int max_count)
Enumerate available CAN-type interfaces from /sys/class/net.
Parameters
ifnames Output array of name buffers.
max_count Capacity of ifnames.
Returns
Number of interfaces written.
< Max interface-name buffer size (incl. NUL).
Definition at line 574 of file socketcan.c.
References count, and SOCKETCAN_MAX_IFACE.
Referenced by populate_interfaces().