PCAN-View Linux: can_driver Struct Reference
can_driver Struct Reference
CAN driver vtable — implemented by each concrete back-end.
#include <drv_can.h>
Data Fields
int(* init)(const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Open/configure the interface.
int(* deinit)(void)
Close the interface.
int(* send)(const can_msg_t *msg)
Transmit one frame.
int(* recv)(can_msg_t *msg, int timeout_ms)
Receive one frame.
int(* get_stats)(can_stats_t *stats)
Query statistics.
int(* set_filter)(uint32_t id, uint32_t mask, int is_extended)
Install an acceptance filter.
int(* clear_filter)(void)
Remove all filters.
int(* reset)(void)
Reset the interface.
const char *(* error_string)(int err)
Map a code to text.
Detailed Description
CAN driver vtable — implemented by each concrete back-end.
Every member is a function pointer mirroring one drv_can_* wrapper.
Definition at line 73 of file drv_can.h.
Field Documentation
init
int(* can_driver::init) (const char *iface, uint32_t bitrate, uint32_t data_bitrate, int fd_mode, int listen_only, const can_bit_timing_t *timing)
Open/configure the interface.
See also
drv_can_init
Definition at line 75 of file drv_can.h.
Referenced by drv_can_init().
deinit
int(* can_driver::deinit) (void)
Close the interface.
Definition at line 79 of file drv_can.h.
Referenced by drv_can_deinit().
send
int(* can_driver::send) (const can_msg_t *msg)
Transmit one frame.
Definition at line 80 of file drv_can.h.
Referenced by drv_can_send().
recv
int(* can_driver::recv) (can_msg_t *msg, int timeout_ms)
Receive one frame.
Definition at line 81 of file drv_can.h.
Referenced by drv_can_recv().
get_stats
int(* can_driver::get_stats) (can_stats_t *stats)
Query statistics.
Definition at line 82 of file drv_can.h.
Referenced by drv_can_get_stats().
set_filter
int(* can_driver::set_filter) (uint32_t id, uint32_t mask, int is_extended)
Install an acceptance filter.
Definition at line 83 of file drv_can.h.
Referenced by drv_can_set_filter().
clear_filter
int(* can_driver::clear_filter) (void)
Remove all filters.
Definition at line 84 of file drv_can.h.
Referenced by drv_can_clear_filter().
reset
int(* can_driver::reset) (void)
Reset the interface.
Definition at line 85 of file drv_can.h.
Referenced by drv_can_reset().
error_string
const char *(* can_driver::error_string) (int err)
Map a code to text.
Definition at line 86 of file drv_can.h.
Referenced by drv_can_error_string().
The documentation for this struct was generated from the following file:
inc/drv_can.h