PCAN-View Linux: gui/threads.c File Reference
threads.c File Reference
Background worker threads, global state, and connect/disconnect logic.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <time.h>
#include <pthread.h>
#include <glib.h>
#include <gtk/gtk.h>
#include "../inc/app_state.h"
#include "../inc/drv_can.h"
#include "../inc/gui.h"
#include "../inc/can_message.h"
Macros
#define TRACE_BUF_MAX 2000000u
Hard cap so a long run can't exhaust RAM.
Functions
void app_state_init (void)
Initialise g_app (queues, mutexes, default settings).
void app_state_cleanup (void)
Disconnect if needed and release all g_app resources.
static gboolean idle_add_message (gpointer data)
Idle callback: hand a received frame to the trace view.
static gboolean idle_update_stats (gpointer data)
Idle callback: refresh the statistics bar on the GTK thread.
static void trace_record (const can_msg_t *msg)
Append one frame to the in-memory trace buffer.
void * thread_rx (void *arg)
Receive-thread entry point.
void * thread_tx (void *arg)
Transmit-thread entry point.
void * thread_stats (void *arg)
Statistics-thread entry point.
void app_do_connect (void)
Open the interface in g_app and start the worker threads.
void app_do_disconnect (void)
Stop the worker threads and close the interface.
Variables
app_state_t g_app
Global application state singleton.
gui_widgets_t g_gui
Global GUI widget registry singleton.
Detailed Description
Background worker threads, global state, and connect/disconnect logic.
Defines the application singletons g_app and g_gui and their lifecycle (app_state_init / app_state_cleanup). Hosts the three worker threads — thread_rx, thread_tx, and thread_stats — which communicate results back to the GTK main thread via gdk_threads_add_idle(). Also implements the in-memory trace capture (trace_record) and the app_do_connect / app_do_disconnect lifecycle that starts and joins the threads.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file threads.c.
Macro Definition Documentation
TRACE_BUF_MAX
#define TRACE_BUF_MAX 2000000u
Hard cap so a long run can't exhaust RAM.
Definition at line 127 of file threads.c.
Function Documentation
app_state_init()
void app_state_init (void)
Initialise g_app (queues, mutexes, default settings).
< Max interface-name length in app state.
Definition at line 44 of file threads.c.
References APP_DATA_FORMAT_HEX, APP_ID_FORMAT_HEX, APP_MAX_IFACE_LEN, app_state_t::bitrate, app_state_t::data_bitrate, app_state_t::data_format, app_state_t::dedup_mutex, g_app, g_gui, app_state_t::id_format, app_state_t::iface, app_state_t::rx_queue, app_state_t::trace_mutex, and app_state_t::tx_queue.
Referenced by main().
app_state_cleanup()
void app_state_cleanup (void)
Disconnect if needed and release all g_app resources.
Definition at line 61 of file threads.c.
References app_do_disconnect(), app_state_t::connected, app_state_t::dedup_mutex, app_state_t::dedup_table, g_app, app_state_t::rx_queue, app_state_t::trace_buf, app_state_t::trace_cap, app_state_t::trace_file, app_state_t::trace_len, app_state_t::trace_mutex, and app_state_t::tx_queue.
Referenced by main().
idle_add_message()
static gboolean idle_add_message (gpointer data) static
Idle callback: hand a received frame to the trace view.
Parameters
data Heap can_msg_t* (freed here).
Returns
G_SOURCE_REMOVE (one-shot).
Definition at line 101 of file threads.c.
References g_app, g_gui, gui_add_message(), app_state_t::shutting_down, and gui_widgets_t::trace_store.
Referenced by thread_rx().
idle_update_stats()
static gboolean idle_update_stats (gpointer data) static
Idle callback: refresh the statistics bar on the GTK thread.
Parameters
data Unused.
Returns
G_SOURCE_REMOVE (one-shot).
Definition at line 115 of file threads.c.
References g_app, g_gui, gui_update_stats(), gui_widgets_t::lbl_rx, and app_state_t::shutting_down.
Referenced by thread_stats(), and thread_tx().
trace_record()
static void trace_record (const can_msg_t * msg) static
Append one frame to the in-memory trace buffer.
Called from the RX and TX worker threads, so it is guarded by g_app.trace_mutex (shared with the CSV writer on the GTK thread). The buffer grows geometrically and stops at TRACE_BUF_MAX frames.
Parameters
msg Frame to capture (copied by value).
< Hard cap so a long run can't exhaust RAM.
Definition at line 138 of file threads.c.
References g_app, app_state_t::trace_buf, TRACE_BUF_MAX, app_state_t::trace_cap, app_state_t::trace_len, app_state_t::trace_mutex, and app_state_t::tracing.
Referenced by thread_rx(), and thread_tx().
thread_rx()
void * thread_rx (void * arg)
Receive-thread entry point.
Parameters
arg Unused.
Returns
NULL.
< Operation succeeded.
< Frame direction: received.
Definition at line 163 of file threads.c.
References CAN_DIR_RX, can_msg_t::direction, can_msg_t::dlc, DRV_CAN_OK, drv_can_recv(), app_state_t::error_count, g_app, idle_add_message(), can_msg_t::is_error, can_msg_t::is_extended, app_state_t::msg_seq, app_state_t::period_bits, app_state_t::rx_count, app_state_t::rx_running, can_msg_t::seq, and trace_record().
Referenced by app_do_connect().
thread_tx()
void * thread_tx (void * arg)
Transmit-thread entry point.
Parameters
arg Unused.
Returns
NULL.
< Operation succeeded.
< Frame direction: transmitted.
Definition at line 204 of file threads.c.
References CAN_DIR_TX, can_msg_t::direction, DRV_CAN_OK, drv_can_send(), g_app, idle_update_stats(), app_state_t::msg_seq, can_msg_t::seq, can_msg_t::timestamp, trace_record(), app_state_t::tx_count, app_state_t::tx_queue, and app_state_t::tx_running.
Referenced by app_do_connect().
thread_stats()
void * thread_stats (void * arg)
Statistics-thread entry point.
Parameters
arg Unused.
Returns
NULL.
Definition at line 240 of file threads.c.
References app_state_t::bitrate, app_state_t::bus_load, app_state_t::connected, g_app, idle_update_stats(), app_state_t::period_bits, and app_state_t::stats_running.
Referenced by app_do_connect().
app_do_connect()
void app_do_connect (void)
Open the interface in g_app and start the worker threads.
< Operation succeeded.
< Error-active bus state.
Definition at line 274 of file threads.c.
References app_state_t::bit_timing, app_state_t::bitrate, app_state_t::bus_load, app_state_t::bus_state, CAN_BUS_ACTIVE, app_state_t::connected, app_state_t::data_bitrate, drv_can_error_string(), drv_can_get_socketcan(), drv_can_init(), DRV_CAN_OK, app_state_t::error_count, app_state_t::fd_mode, g_app, g_gui, gui_show_error(), gui_status_message(), gui_tx_panel_update_fd(), app_state_t::iface, app_state_t::listen_only, app_state_t::msg_seq, app_state_t::period_bits, app_state_t::rx_count, app_state_t::rx_running, app_state_t::rx_thread, app_state_t::stats_running, app_state_t::stats_thread, thread_rx(), thread_stats(), thread_tx(), gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, app_state_t::tx_count, app_state_t::tx_running, app_state_t::tx_thread, and gui_widgets_t::window.
Referenced by gui_show_settings_dialog().
app_do_disconnect()
void app_do_disconnect (void)
Stop the worker threads and close the interface.
Definition at line 337 of file threads.c.
References app_state_t::connected, drv_can_deinit(), g_app, g_gui, gui_status_message(), gui_update_stats(), app_state_t::iface, app_state_t::rx_running, app_state_t::rx_thread, app_state_t::shutting_down, app_state_t::stats_running, app_state_t::stats_thread, gui_widgets_t::toolbar_connect, gui_widgets_t::toolbar_disconnect, gui_widgets_t::toolbar_trace_start, gui_widgets_t::toolbar_trace_stop, app_state_t::tracing, app_state_t::tx_running, and app_state_t::tx_thread.
Referenced by app_state_cleanup(), gui_show_settings_dialog(), on_disconnect(), on_quit(), and on_window_delete().
Variable Documentation
g_app
app_state_t g_app
Global application state singleton.
The process-wide application state singleton (defined in threads.c).
Definition at line 37 of file threads.c.
Referenced by app_do_connect(), app_do_disconnect(), app_state_cleanup(), app_state_init(), build_frame(), build_menubar(), cyclic_tick(), gui_format_data(), gui_format_id(), gui_show_settings_dialog(), gui_tx_panel_update_fd(), gui_update_stats(), idle_add_message(), idle_update_stats(), on_data_format_toggle(), on_dedup_toggle(), on_id_format_toggle(), on_trace_save(), on_trace_start(), on_trace_stop(), populate_interfaces(), send_frame(), should_rollup_message(), thread_rx(), thread_stats(), thread_tx(), trace_record(), txp_add_row(), txp_build_frame(), txp_cyclic_tick(), txp_queue_frame(), and txp_start_cyclic().
g_gui
gui_widgets_t g_gui
Global GUI widget registry singleton.
The process-wide GUI widget registry (defined in threads.c).
Definition at line 38 of file threads.c.
Referenced by app_do_connect(), app_do_disconnect(), app_state_init(), build_stats_bar(), build_toolbar(), create_stats_panel(), create_trace_view(), gui_add_message(), gui_clear_trace(), gui_create_main_window(), gui_refresh_trace_display(), gui_show_transmit_window(), gui_status_message(), gui_update_stats(), idle_add_message(), idle_update_stats(), on_about(), on_connect(), on_quit(), on_settings(), on_trace_save(), on_trace_start(), and on_trace_stop().