PCAN-View Linux: gui/transmit_dialog.c File Reference
transmit_dialog.c File Reference
Advanced ("Transmit...") CAN/CAN FD message composer window.
#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <ctype.h>
#include <errno.h>
#include <gtk/gtk.h>
#include "../inc/gui.h"
#include "../inc/app_state.h"
#include "../inc/can_message.h"
Data Structures
struct tx_win_t
Widget state for the advanced transmit window (singleton s_tx).
Macros
#define MAX_DATA_ENTRIES 64
#define TX_STD_ID_MAX 0x7FFu
#define TX_EXT_ID_MAX 0x1FFFFFFFu
#define TX_BYTE_MAX 0xFFu
#define FLABEL(s)
Functions
static int parse_hex_u32 (const char *s, uint32_t max, uint32_t *out)
Strictly parse a hex string into a bounded uint32_t.
static gboolean build_frame (can_msg_t *msg)
Validate the form fields and assemble a can_msg_t.
static void send_frame (void)
Build and enqueue the current frame for transmission.
static gboolean cyclic_tick (gpointer data)
Cyclic-timer callback: send one frame per tick.
static void on_cyclic_start (GtkWidget *w, gpointer d)
"Start Cyclic" handler — arm the periodic send timer.
static void on_cyclic_stop (GtkWidget *w, gpointer d)
"Stop Cyclic" handler — disarm the periodic send timer.
static void update_data_fields (void)
Re-range the DLC spin and enable exactly the active data-byte fields.
static void on_fd_toggled (GtkToggleButton *b, gpointer d)
CAN FD toggle handler.
static void on_dlc_changed (GtkSpinButton *b, gpointer d)
DLC spin change handler.
static void on_rtr_toggled (GtkToggleButton *b, gpointer d)
Remote-frame toggle handler.
static void on_send_once (GtkWidget *w, gpointer d)
"Send Once" handler.
static void on_tx_win_destroy (GtkWidget *w, gpointer d)
Window destroy handler — cancel the cyclic timer and clear state.
void gui_show_transmit_window (void)
Show the advanced transmit window.
Variables
static tx_win_t s_tx
The single advanced-transmit window instance.
Detailed Description
Advanced ("Transmit...") CAN/CAN FD message composer window.
A non-modal secondary window for hand-crafting a single frame with full control over: identifier (hex) and standard/extended flag, data vs. remote (RTR) frame, CAN FD + BRS, DLC (0..8 classic, 0..64 FD), individual data bytes, and one-shot or cyclic transmission at a configurable interval. Frames are validated by build_frame and pushed onto g_app.tx_queue.
Author
Subhajit Roy subha.nosp@m.jitr.nosp@m.oy005.nosp@m.@gma.nosp@m.il.co.nosp@m.m
Date
2026
Copyright
SPDX-License-Identifier: Apache-2.0
Definition in file transmit_dialog.c.
Macro Definition Documentation
MAX_DATA_ENTRIES
#define MAX_DATA_ENTRIES 64
Definition at line 33 of file transmit_dialog.c.
TX_STD_ID_MAX
#define TX_STD_ID_MAX 0x7FFu
Definition at line 34 of file transmit_dialog.c.
TX_EXT_ID_MAX
#define TX_EXT_ID_MAX 0x1FFFFFFFu
Definition at line 35 of file transmit_dialog.c.
TX_BYTE_MAX
#define TX_BYTE_MAX 0xFFu
Definition at line 36 of file transmit_dialog.c.
FLABEL
#define FLABEL (s)
Value:
    do { \
    GtkWidget *_l = gtk_label_new(s); \
    gtk_label_set_xalign(GTK_LABEL(_l), 1.0f); \
    gtk_grid_attach(GTK_GRID(frm_grid), _l, 0, r, 1, 1); \
} while(0)
Function Documentation
parse_hex_u32()
static int parse_hex_u32 (const char * s, uint32_t max, uint32_t * out) static
Strictly parse a hex string into a bounded uint32_t.
Parameters
s Input text.
max Maximum allowed value.
out Result.
Returns
0 on success, -1 on malformed input or overflow.
Definition at line 68 of file transmit_dialog.c.
Referenced by build_frame().
build_frame()
static gboolean build_frame (can_msg_t * msg) static
Validate the form fields and assemble a can_msg_t.
Parameters
msg Output frame.
Returns
TRUE if valid (status label cleared), FALSE on a validation error.
Definition at line 92 of file transmit_dialog.c.
References tx_win_t::brs_check, can_msg_t::data, tx_win_t::data_entry, can_msg_t::dlc, tx_win_t::dlc_spin, tx_win_t::ext_check, tx_win_t::fd_check, app_state_t::fd_mode, g_app, can_msg_t::id, tx_win_t::id_entry, can_msg_t::is_brs, can_msg_t::is_extended, can_msg_t::is_fd, can_msg_t::is_remote, parse_hex_u32(), tx_win_t::rtr_check, s_tx, tx_win_t::status_label, TX_BYTE_MAX, TX_EXT_ID_MAX, and TX_STD_ID_MAX.
Referenced by send_frame().
send_frame()
static void send_frame (void) static
Build and enqueue the current frame for transmission.
Definition at line 153 of file transmit_dialog.c.
References build_frame(), app_state_t::connected, g_app, s_tx, tx_win_t::status_label, and app_state_t::tx_queue.
Referenced by cyclic_tick(), and on_send_once().
cyclic_tick()
static gboolean cyclic_tick (gpointer data) static
Cyclic-timer callback: send one frame per tick.
Parameters
data Unused.
Returns
Continue/remove.
Definition at line 177 of file transmit_dialog.c.
References app_state_t::connected, tx_win_t::cyclic_timer_id, g_app, s_tx, and send_frame().
Referenced by on_cyclic_start().
on_cyclic_start()
static void on_cyclic_start (GtkWidget * w, gpointer d) static
"Start Cyclic" handler — arm the periodic send timer.
Parameters
w Widget.
d Unused.
Definition at line 186 of file transmit_dialog.c.
References tx_win_t::cyclic_btn_start, tx_win_t::cyclic_btn_stop, cyclic_tick(), tx_win_t::cyclic_timer_id, tx_win_t::interval_spin, and s_tx.
Referenced by gui_show_transmit_window().
on_cyclic_stop()
static void on_cyclic_stop (GtkWidget * w, gpointer d) static
"Stop Cyclic" handler — disarm the periodic send timer.
Parameters
w Widget.
d Unused.
Definition at line 201 of file transmit_dialog.c.
References tx_win_t::cyclic_btn_start, tx_win_t::cyclic_btn_stop, tx_win_t::cyclic_timer_id, s_tx, and tx_win_t::status_label.
Referenced by gui_show_transmit_window().
update_data_fields()
static void update_data_fields (void) static
Re-range the DLC spin and enable exactly the active data-byte fields.
Definition at line 218 of file transmit_dialog.c.
References tx_win_t::brs_check, tx_win_t::data_entry, tx_win_t::dlc_spin, tx_win_t::fd_check, MAX_DATA_ENTRIES, tx_win_t::rtr_check, and s_tx.
Referenced by on_dlc_changed(), on_fd_toggled(), and on_rtr_toggled().
on_fd_toggled()
static void on_fd_toggled (GtkToggleButton * b, gpointer d) static
CAN FD toggle handler.
Parameters
b Button.
d Unused.
Definition at line 242 of file transmit_dialog.c.
References update_data_fields().
Referenced by gui_show_transmit_window().
on_dlc_changed()
static void on_dlc_changed (GtkSpinButton * b, gpointer d) static
DLC spin change handler.
Parameters
b Spin button.
d Unused.
Definition at line 249 of file transmit_dialog.c.
References update_data_fields().
Referenced by gui_show_transmit_window().
on_rtr_toggled()
static void on_rtr_toggled (GtkToggleButton * b, gpointer d) static
Remote-frame toggle handler.
Parameters
b Button.
d Unused.
Definition at line 256 of file transmit_dialog.c.
References update_data_fields().
Referenced by gui_show_transmit_window().
on_send_once()
static void on_send_once (GtkWidget * w, gpointer d) static
"Send Once" handler.
Parameters
w Widget.
d Unused.
Definition at line 267 of file transmit_dialog.c.
References send_frame().
Referenced by gui_show_transmit_window().
on_tx_win_destroy()
static void on_tx_win_destroy (GtkWidget * w, gpointer d) static
Window destroy handler — cancel the cyclic timer and clear state.
Parameters
w Widget.
d Unused.
Definition at line 274 of file transmit_dialog.c.
References tx_win_t::cyclic_timer_id, s_tx, and tx_win_t::window.
Referenced by gui_show_transmit_window().
gui_show_transmit_window()
void gui_show_transmit_window (void)
Show the advanced transmit window.
Definition at line 284 of file transmit_dialog.c.
References tx_win_t::brs_check, tx_win_t::cyclic_btn_start, tx_win_t::cyclic_btn_stop, tx_win_t::data_entry, tx_win_t::data_grid, tx_win_t::dlc_spin, tx_win_t::ext_check, tx_win_t::fd_check, FLABEL, g_gui, tx_win_t::id_entry, tx_win_t::interval_spin, MAX_DATA_ENTRIES, on_cyclic_start(), on_cyclic_stop(), on_dlc_changed(), on_fd_toggled(), on_rtr_toggled(), on_send_once(), on_tx_win_destroy(), tx_win_t::rtr_check, s_tx, tx_win_t::status_label, tx_win_t::window, and gui_widgets_t::window.
Referenced by on_transmit().
Variable Documentation
s_tx
tx_win_t s_tx static
The single advanced-transmit window instance.
Definition at line 57 of file transmit_dialog.c.
Referenced by build_frame(), cyclic_tick(), gui_show_transmit_window(), on_cyclic_start(), on_cyclic_stop(), on_tx_win_destroy(), send_frame(), and update_data_fields().